export const BHAGWANPUR_1_OPTIONS = [
  "1 - Barbhagwanpur Primary School",
  "2 - Barbhagwanpur Primary School",
  "3 - Banamalipur Primary School",
  "4 - Banamalipur Sishu Siksha Kendra",
  "5 - Nunhanda Kshudiram M.S.K",
  "6 - Nunhanda Palli Vidyapith",
  "7 - Nunhanda Palli Vidyapith",
  "8 - Talda Primary School",
  "9 - Chinyaandulia Board Prathamik vidyalay",
  "10 - Shyamchak Primary School",
  "11 - Srikantapur Prathamik vidyalay",
  "12 - Kulberia Prathamik vidyalay",
  "13 - Kulberia Prathamik vidyalay",
  "14 - Simulia s.K.u.s. Limited",
  "15 - Baman Simulia Prathamik vidyalay",
  "16 - Bhimeswari Uchha sikshayatan",
  "17 - Bhimeswari Balika vidyapith",
  "18 - Bartan Special Primary School",
  "19 - Bartan Special Primary School",
  "20 - Unal Primary School",
  "21 - Katgechhia Primary School",
  "22 - Kishorpur Sridurga Prathamik vidyalay",
  "23 - Rampur Primary School",
  "24 - Illashpur Stateplane Prathamik vidyalaya",
  "25 - Illashpur Harijan Board Prathamik vidyalaya",
  "26 - Barbasudebpur Primary School",
  "27 - Paikbheri Shyamsundar Primary School",
  "28 - Kuber Dutta Veri Sishu Siksha Kendra",
  "29 - Kalurbheri Prathamik vidyalay",
  "30 - Kalurbheri Prathamik vidyalay",
  "31 - Dakshin Bishnupur Prathamik vidyalaya",
  "32 - Uttar Bishnupur Primary School",
  "33 - Bachhipur Sishu Siksha Kendra",
  "34 - Bachhipur Atyayik Prathamik Vidyalaya",
  "35 - Bhagwanpur Highschool",
  "36 - Bhagwanpur State Plan Prathamik vidyalay",
  "37 - Durgapur Board Prathamik vidyalay",
  "38 - Jalibarh Prymary School",
  "39 - Paschim Ghoshpur Primary School",
  "40 - Shibarampur Atyaik Pry.School",
  "41 - Uttar Bhagwanpur Nabarun vidyapith",
  "42 - Khaga Board Prathamik vidyalaya",
  "43 - Babia Prathamik vidyalaya",
  "44 - Sarangapur Prathamik Vidyalaya",
  "45 - Abasberia Adarsha vidyapith(highschooll)",
  "46 - Abasberia Board Primary School",
  "47 - Baraibar Board Prathamik vidyalay",
  "48 - Baraibarh New Pry.School",
  "49 - Jagamohanpur Primary School",
  "50 - Lohabar Prathamik vidyalaya",
  "51 - Paschim Sarberia Ojuda Madhyamik Siksha Kendra",
  "52 - Sarberia Uchha Prathamik Maktab vidyalaya",
  "53 - Sarberia Board Prathamik vidyalaya",
  "54 - Bhabanichak Prathamik vidyalaya",
  "55 - Hinchageria Stateplan Primary School",
  "56 - Hinchageria Stateplan Primary School",
  "57 - Hinchageria Special cader Primary School",
  "58 - Hinchageria Special cader Primary School",
  "59 - Narayandari Natun Prathamik vidyalaya",
  "60 - Narayandari Board Primary School",
  "61 - Bajaberia Prathamik vidyalaya",
  "62 - Narayandari Barbajaberia Natun Primary vidyalaya",
  "63 - Tethibari State Plan Primary School",
  "64 - Kaptyabari Board (Atyayik) Prathamik vidyalaya",
  "65 - Dakshin Kaptyabari Bishnuhari Primary School",
  "66 - Kajlagar M.S.B.C.M. Highschool",
  "67 - Kajlagar Uchha Prathamik vidyalaya",
  "68 - Mirjapur Pry.School",
  "69 - Sujamutha-Manoharpur Uchcha Prathamik vidyalaya",
  "70 - Dayalchak Primary vidyalaya",
  "71 - Purbaradhapur Jitnarayan Prathamik vidyalaya",
  "72 - Purbaradhapur Jitnarayan Prathamik vidyalaya",
  "73 - Shukrullapur Board Prathamik vidyalay",
  "74 - Shukrullapur Atyayik Uchcha Prathamik vidyalaya",
  "75 - Shukrullapur Atyayik Uchcha Prathamik vidyalaya",
  "76 - Deuribar Kiranprabha vidyamandir",
  "77 - Ashutia Sarojini vidyapith (Highschooll)",
  "78 - Ashutia Sarojini vidyapith (Highschooll)",
  "79 - Balaramchak Primary School",
  "80 - Shyamchak Radhakrishna Uchcha Prathamik vidyalaya",
  "81 - Gumkia Shyamchak Atyaik Primary School",
  "82 - Charabar Girls Prathamik vidyalaya",
  "83 - Shyamchak Radhakrishna Uchcha Prathamik vidyalaya",
  "84 - Charabar Girls Highschool",
  "85 - Charabar Girls Highschool",
  "86 - Kalaberia Primary School (Daspara)",
  "87 - Kalaberia Primary School (Daspara)",
  "88 - Kotbarh Board Primary School",
  "89 - Kotbarh vidyasundari Primary School",
  "90 - Chowdunia Pry.School",
  "91 - Dalbar Ramnarayan Prathamik vidyalaya",
  "92 - Kotbarh Maktab Prathamik vidyalay",
  "93 - Kotbarh vidyasundari Primary School",
  "94 - Kotbarh Maktab Prathamik vidyalay",
  "129 - Khetrapal Chakbhogi Atyayik Prathamik vidyalay",
  "130 - Khetrapal Chakbhogi Atyayik Prathamik vidyalay",
  "131 - Chakbhogi Prathamik vidyalay",
  "132 - Ballyagobindapur Board Pry.School",
  "133 - Ballyagobindapur Balika Vidyalaya",
  "134 - Ballyagobindapur Gnankarma Vidyapith(Uttarngsha)",
  "135 - Balyagobindapur gankarma vidyapith (Dakshinangsha)",
  "136 - Chandankhali Prathamik vidyalay",
  "137 - Madanmohanpur Draupadi Sundari Prathamik vidyalay",
  "138 - Panchagram Sikshaniketan",
  "139 - Uttar Itaberia Prathamik vidyalay",
  "140 - Hakimpur Prathamik vidyalay",
  "141 - Budhijore Prathamik vidyalay",
  "142 - Bhubanmangalpur Prathamik vidyalay",
  "143 - Saradabarh Srihari Vidyapith",
  "144 - Pania Saradabar Ramkrishna Sikshasadan",
  "145 - Mathura Prathamik vidyalay (Uttarangsha)",
  "146 - Mathura Prathamik vidyalay (Dakshinangsha)",
  "147 - Tahalia Deulbar Prathamik vidyalay",
  "148 - Mangraj Prathamik vidyalay",
  "149 - Lalua Chakrashul Board Prathamik vidyalay",
  "150 - Lalua Adarsha Prathamik Bidyalay (East)",
  "151 - Lalua Adarsha Prathamik vidyalay",
  "152 - Chakpadu Prathamik vidyalay",
  "153 - Argoal Nankar Prathamik vidyalay",
  "154 - Argoal Board Prathamik vidyalay",
  "155 - Jabda vidyasagar vidyapith (Purbangsha)",
  "156 - Jabda vidyasagar vidyapith ( Paschimangsha)",
  "157 - Dakshin lawa Pry.School",
  "158 - Kakhuria Bapuji Prathamik vidyalay",
  "159 - Paschim Lawa SSK",
  "160 - Mangalchak Saraswati Prathamik vidyalay",
  "161 - Khatibarh Haripur Jr. High School",
  "162 - Nekursini Krishishilpa Siksha Sadan(Highschooll)",
  "163 - Taniabila Prathamik vidyalay",
  "164 - Babuidanri Prathamik vidyalay",
  "165 - Sinyari Harijan Nimna Buniadi vidyalay",
  "166 - Braja Ballavpur Pry. School",
  "167 - Samaspur Bishnupriya Balika vidyalay(Ju:high School)",
  "168 - Uttar Sandalpur Free Prathamik vidyalay",
  "169 - Dakshin Sandalpur Prathamik vidyalay",
  "170 - Ichchhabari Kunjabihari Special Prathamik vidyalay",
  "171 - Kourmoishali Pry.School",
  "172 - Paninala Prathamik Vidyalaya",
  "173 - Satshatamal Special Prathamik vidyalay",
  "174 - Satshatamal Board Prathamik vidyalay",
];

export const BHAGWANPUR_2_OPTIONS = [
  "95 - Ururi Primary School",
  "96 - Ururi Primary School",
  "97 - Chinadanri Primary School",
  "98 - Bahadurpur 3No Primary School",
  "99 - Bahadurpur I.C.J.C.K.",
  "100 - Bahadurpur 2No Primary School",
  "101 - Bahadurpur Purbapara SSK",
  "102 - Bahadurpur Desapran Sikshaniketan Highschool",
  "103 - Iswarpur Junior Basic School",
  "104 - Sankhadiha Primary School",
  "105 - Machnan Primary School",
  "106 - Madhabpur Indranarayan Highschooll",
  "107 - Haripur Highschool",
  "108 - Radhapur Prabin Primary School",
  "109 - Radhapur Muslim Palli Primary School",
  "110 - Dakshin Radhapur Haracharan SSK",
  "111 - Kismat Khatiyal Special Kyader Primary School",
  "112 - Barbaria Hazra vidyapith",
  "113 - Simuldanri Primary School",
  "114 - Khatial Primary School",
  "115 - Basudebberia Primary School (Bashuli Bazar)",
  "116 - Basudebberia Primary School (Bashuli Bazar)",
  "117 - Basudebberia Hariparaprimary school",
  "118 - Uttar Pathar Beria Primary School",
  "119 - Manikjore Stateplyan Primary School",
  "120 - Manikjore Harijan Palli Primary School",
  "121 - Konchak Pry.School",
  "122 - Dakshin Patharberia Anandamoyee Balika vidyalay",
  "123 - Dakshin Pathar Beria Primary School",
  "124 - Khantmari Biswanathpur Primary School",
  "125 - Laudighi Primary School",
  "126 - Neturia Primary School",
  "127 - Champainagar S.C. Hihg School",
  "128 - Udbadal Maa Basanti SSK",
  "175 - Pachahari Primary School",
  "176 - Purbahari SSK",
  "177 - Dubai Rasiknagar vivekananda Highschool (Purbangsha)",
  "178 - Dubai Primary School",
  "179 - Maishali Primary School",
  "180 - Jiakhali Primary School",
  "181 - Uttar Khamar Primary School",
  "182 - Alukaranbar Pry.School",
  "183 - Panchbajari Primary School",
  "184 - Purbabajari Primary School",
  "185 - Teghari Primary School",
  "186 - Bamanbar Primary School",
  "187 - Kotmukha Primary School",
  "188 - Kotmukha Primary School",
  "189 - Jashibar Primary School",
  "190 - Jashibar Primary School",
  "191 - Kunjapara Primary School",
  "192 - Itaberia State Plan Primary School",
  "193 - Itaberia Primary School,(Bazar Said)Purbangsha",
  "194 - Asfhakulla SSK",
  "195 - Haridrachak Primary School",
  "196 - Kamal Nayanbar Primary School",
  "197 - Uttardigha Primary School",
  "198 - Dhaipukuria Primary School",
  "199 - Dhaipukuria State Plan pry.School",
  "200 - Naruabila Junior highschool",
  "201 - Madhyabila Primary School",
  "202 - Parulia Primary School",
  "203 - Arjunnagar 2No Primary School (Paschimangsha)",
  "204 - Arjunnagar MSK",
  "205 - Arjunnagar 2No Primary School (Paschimangsha)",
  "206 - Arjunnagar 1 No Prathamik vidyalay",
  "207 - Ratnajore Primary School",
  "208 - Khejur Gachhia Bhoslageria Primary School",
  "209 - Kalmichhabar Primary School",
  "210 - Analberia Primary School",
  "211 - Nijnarua Primary School",
  "212 - Ichchhabari highschool",
  "213 - Chingra Primary School",
  "214 - Janumanu Primary vidyalay",
  "215 - Kismat Patna Primary School",
  "216 - Dumurdari Raghunath high school",
  "217 - Padmatamli Primary School",
  "218 - Padmatamli Harijan Palli Pry.School",
  "219 - Bayenda Board Primary School",
  "220 - Dakshin Bayenda Pry. School",
  "221 - Ichchhapur Primary School",
  "222 - Panchghari Primary School",
  "223 - Garabar Primary School",
  "224 - Keshaidighi Primary School",
  "225 - Keshaidighi Primary School",
  "226 - Khanjadapur Rajbangshi Primary School",
  "227 - Khanjadapur SSK",
  "228 - Paschim Kalagechhiya Primary vidyalay",
  "229 - Mugberia Gangadhar High School",
  "230 - Bhupatinagar Kanya vidyalay",
  "231 - Bhupatinagar Primary School (Pradhan Para) Purbangsha",
  "232 - Bhupatinagar parya para s.s.k",
  "233 - Angarberia Primary School",
  "234 - Raghunathchak Junior Highschool",
  "235 - Jiagodi SSK",
  "236 - Mulda Primary School",
  "237 - Kayemgeria D,M,Highschooll (Purbangsha)",
  "238 - Kayemgeria D,M,Highschooll ()",
  "239 - Uttar Baroj Primary School",
  "240 - Dakshin Baroj 2nd Khanda Primary School",
  "241 - Shimulbari Primary School",
  "242 - Diha Shimulia Primary School",
  "243 - Kayemgeria Primary School",
  "244 - Uttar Nischinta Primary School",
  "245 - Dakshin Mahishda Primary School",
  "246 - Dighadanri Primary School",
  "247 - Uttar Bijay Nagar Primary School",
  "248 - Dakshin Bijaynagar S.S.K",
  "249 - Paunshi Annapurna Nimna Buniadi vidyalay",
  "250 - Pausi Baikuntha Smriti Milani Vidyamandir",
  "251 - Chirakuti Primary School",
  "252 - Gholbagda Primary School",
  "253 - Kutubuddinpur Primary School",
  "254 - Madhakhali Primary School",
  "255 - Garania Primary School",
  "256 - Gobindachak Special Kyader Primary school",
  "257 - Sadulyachak Primary School",
  "258 - Ikshu Patrika Primary School(Purbangsha)",
  "259 - Ikshu Patrika Primary School(Purbangsha)",
  "260 - Jukhiasitadighispecial Kyader Primaryschool(Purbangsha)",
  "261 - Jukhiasitadighispecial Kyader Primaryschool(Purbangsha)",
  "262 - Jukhia Ramhari Primary School",
  "263 - Sita Dighi Primary School",
  "264 - Bamunia Primary School",
  "265 - Jukhia K.N.Banimandir (High School)",
  "266 - Dhelua Primary School",
  "267 - Nelua Primary School",
  "268 - Gopalchak SSK",
  "269 - Ramchak Primary School (Purbangsha)",
  "270 - Ramchak Primary School (Purbangsha)",
  "271 - Ramchak new Primary School",
  "272 - Biribari Primary School",
  "273 - Kantapukuria New Primary School",
  "274 - Kantapukhuria Board Pry.School",
  "275 - Baghadanri high School",
  "276 - Baghadanri Primary School",
  "277 - Baghadanri Primary School",
  "278 - Ektarpur I.C.D.S. Center",
  "279 - Ektarpur Pry. School(Paschimangsha) PART -  1",
  "280 - Ektarpur Primary School(Paschimangsha)Part  - 2",
];

export const BHAGWANPUR_1_MAP_OPTIONS = [
  "https://maps.app.goo.gl/ncXcrunPD3kPg52M7 ",
  "https://maps.app.goo.gl/MjUAPSXq1d1RugMG7 ",
  "https://maps.app.goo.gl/NdGbvWwPQBrECbTcA ",
  "https://maps.app.goo.gl/6q3FYsk9CVDvbvng9 ",
  "https://maps.app.goo.gl/Fx2DniPU7SawLkvL6 ",
  "https://maps.app.goo.gl/NdGbvWwPQBrECbTcA ",
  "https://maps.app.goo.gl/YGkQqZ4PJzaZ5j1AA ",
  "https://maps.app.goo.gl/nkXuHsa6SNavoLAF7 ",
  "https://maps.app.goo.gl/26A6BoVCR7GbK1GY9 ",
  "https://maps.app.goo.gl/W23ZmsG6A68Xco1K6 ",
  "https://maps.app.goo.gl/ZjK69CUfkzG54WfF9 ",
  "https://maps.app.goo.gl/8HyH5EHcqCnNtUXx6 ",
  "https://maps.app.goo.gl/8DJ9DqRTHE5jnjKw9 ",
  "https://maps.app.goo.gl/FvYJ99rdHuv88MHt9 ",
  "https://maps.app.goo.gl/Bufmox6zofwGo2J29 ",
  "https://maps.app.goo.gl/pJHXYVydgBU8mcUQ8 ",
  "https://maps.app.goo.gl/RvCXA1QQ6u7osKfZ6 ",
  "https://maps.app.goo.gl/ycw5YPasxnSUePub8 ",
  "https://maps.app.goo.gl/ycw5YPasxnSUePub8 ",
  "https://maps.app.goo.gl/5dBDJXXFCzkbiqF6A ",
  "https://maps.app.goo.gl/teqAKRoRMH5aTTDu8 ",
  "https://maps.app.goo.gl/i6p5oxrk8fgNRxcR7 ",
  "https://maps.app.goo.gl/BRzyniE8K2Wf11SA7 ",
  "https://maps.app.goo.gl/86Swf9UCabz3AGMj6  ",
  "https://maps.app.goo.gl/LCejWh7nHt77vnsS9 ",
  "https://maps.app.goo.gl/T4gv4LGrqMWyoZYD7  ",
  "https://maps.app.goo.gl/qGQkPZ7vjfNJXzKXA ",
  "https://maps.app.goo.gl/GAXswUHXZRYCvScb6 ",
  "https://maps.app.goo.gl/XjDGMCmNP52VgL3J9 ",
  "https://maps.app.goo.gl/5dkvB76eBj1eK8iM9 ",
  "https://maps.app.goo.gl/j1BAKSrDvnYpjTxw9 ",
  "https://maps.app.goo.gl/UHzq9BPFPJeJSqge8 ",
  "https://maps.app.goo.gl/vDCsLELxQMYDT1tv5 ",
  "https://maps.app.goo.gl/vEk9hEyMhNYqQP9KA ",
  "https://maps.app.goo.gl/kKPKBsDBeRe2jRWD8 ",
  "https://maps.app.goo.gl/5xeE3NZ9AGUotb2V9 ",
  "https://maps.app.goo.gl/uL53Xa6hPc82zb8N6 ",
  "https://maps.app.goo.gl/RrbhUdwVMGMos6CK7 ",
  "https://maps.app.goo.gl/pxJ47ErPEvh9Yweg8 ",
  "https://maps.app.goo.gl/oDUtiYLw9tYm9Ch38 ",
  "https://maps.app.goo.gl/AYxv6P9ZUr9VUnV47 ",
  "https://maps.app.goo.gl/h3fap7L7YEe4oYML7 ",
  "https://maps.app.goo.gl/Xg8tpZCdAVbchcuf6 ",
  "https://maps.app.goo.gl/2GRi6cFLdiiAGsmq8 ",
  "https://maps.app.goo.gl/utBcsNaNtiaXuoRH7 ",
  "https://maps.app.goo.gl/oeuUrxKK6KSyAGTe8 ",
  "https://maps.app.goo.gl/BingGXSSyywUttjj7 ",
  "https://maps.app.goo.gl/cm8W1Rjxu6cwkqBw8 ",
  "https://maps.app.goo.gl/XrfHTx1mgv1qML5T6  ",
  "https://maps.app.goo.gl/cQAnBYEmscYkXA8z7 ",
  "https://maps.app.goo.gl/5CkKdbbgWNEing8g8 ",
  "https://maps.app.goo.gl/Vhb6gRARj7c8NkkC8  ",
  "https://maps.app.goo.gl/rHVaLT9uKAoTLGDRA ",
  "https://maps.app.goo.gl/waG1t8SC3j7XBqL18 ",
  "https://maps.app.goo.gl/4SuhGEp5bD15gTND7 ",
  "https://maps.app.goo.gl/4SuhGEp5bD15gTND7 ",
  "https://maps.app.goo.gl/kSxihbL2L2Hf9Wky5 ",
  "https://maps.app.goo.gl/FkzzDnp22Aa4SiJw9 ",
  "https://maps.app.goo.gl/nPFZ22iGD5iLKD9J9 ",
  "https://maps.app.goo.gl/m4Srw7TxF4ceoz5j8 ",
  "",
  "https://maps.app.goo.gl/gdvwnxjpvj1Neb9V9 ",
  "https://maps.app.goo.gl/Ci5y5eDYY1xsuZRX7 ",
  "https://maps.app.goo.gl/viC4FwgiALNNuooF6 ",
  "https://maps.app.goo.gl/RcptVQcSRRKfQRZx9 ",
  "https://maps.app.goo.gl/wW61gfncpo3wLfgi9 ",
  "https://maps.app.goo.gl/rATL1wvcJ1DmuPAo9 ",
  "https://maps.app.goo.gl/yvkhvvYJCsya45yV9 ",
  "https://maps.app.goo.gl/j3GuAU5djrEvQtvk9 ",
  "https://maps.app.goo.gl/75zptJMQN3p1YDo29 ",
  "https://maps.app.goo.gl/eohemKQnAYVzcixv7 ",
  "https://maps.app.goo.gl/eohemKQnAYVzcixv7 ",
  "https://maps.app.goo.gl/mfD6bwoa7HMpiWsFA ",
  "https://maps.app.goo.gl/xtXCb2yNcL8r3kTK6 ",
  "https://maps.app.goo.gl/bFrhmeGne9rkvLMs8 ",
  "https://maps.app.goo.gl/1KAbu1e1RvWpj1e98 ",
  "https://maps.app.goo.gl/S389onuEvVf4BQUo7 ",
  "https://maps.app.goo.gl/S389onuEvVf4BQUo7 ",
  "https://maps.app.goo.gl/TeY6mbECgB6NWfy27 ",
  "https://maps.app.goo.gl/NP1YtZJ4GVJet7yN7 ",
  "https://maps.app.goo.gl/S8zdEx1pykn72W1s7 ",
  "https://maps.app.goo.gl/WDoQ8aGNhEBgRNAa7 ",
  "https://maps.app.goo.gl/k3qFdPtXvGTYqVzr5 ",
  "https://maps.app.goo.gl/67TqsboBcULy5Krw7 ",
  "https://maps.app.goo.gl/67TqsboBcULy5Krw7 ",
  "https://maps.app.goo.gl/QmYDor69JXUzLDqF7 ",
  "https://maps.app.goo.gl/QmYDor69JXUzLDqF7 ",
  "https://maps.app.goo.gl/6HMZ94vCXN9wVemS9 ",
  "https://maps.app.goo.gl/A1vCT11w8wi2DoTA8 ",
  "https://maps.app.goo.gl/TVWzsGZ7UBoBuxQo6  ",
  "https://maps.app.goo.gl/ai3AXTwpEcZ1NVf29 ",
  "https://maps.app.goo.gl/RkcQEA72S4aYhPaW9 ",
  "https://maps.app.goo.gl/i6NbHmv8qruQoX1Q8 ",
  "https://maps.app.goo.gl/hisPDM5Us45RCwBN6 ",
  "https://maps.app.goo.gl/tKaCCB7Kc8y22Sae7",
  "https://maps.app.goo.gl/tKaCCB7Kc8y22Sae7",
  "https://maps.app.goo.gl/tdD368StarqvYAaYA",
  "https://maps.app.goo.gl/WuZJc5rsyZbW1xCy7",
  "https://maps.app.goo.gl/5vmAWFDzB4NVoyBw6",
  "https://maps.app.goo.gl/b3g3vtcx9ukjQRoaA",
  "https://maps.app.goo.gl/b3g3vtcx9ukjQRoaA",
  "https://maps.app.goo.gl/43JhipgxrFwESqDi8",
  "https://maps.app.goo.gl/DMPFEy4D9NjFgB1p7",
  "https://maps.app.goo.gl/cLxkv7NUMVTBgauY7",
  "https://maps.app.goo.gl/JfgrHJohPYTk89AV6",
  "https://maps.app.goo.gl/SsVA51xLZfVTdJ589",
  "https://maps.app.goo.gl/4teZPGE6DF5Hovd98",
  "https://maps.app.goo.gl/ryUYjWXVEKLzPFqy9",
  "https://maps.app.goo.gl/W9UKKxVVrE8BeJW48",
  "https://maps.app.goo.gl/NjtuUniYvGWbQtHEA",
  "https://maps.app.goo.gl/v4Y4RYBjbeiMGdZc8",
  "https://maps.app.goo.gl/sQrMo9sMuAoKSweb8",
  "https://maps.app.goo.gl/uJtiHoPhYanSuKyh9",
  "https://maps.app.goo.gl/pEFJ9UtMJC2mfTyf9",
  "https://maps.app.goo.gl/nZtr8M6nRSJc78H79",
  "https://maps.app.goo.gl/BCsu8tdShdU99NtWA",
  "https://maps.app.goo.gl/BCsu8tdShdU99NtWA",
  "https://maps.app.goo.gl/3XRDkMuhF6yBRZqw7",
  "https://maps.app.goo.gl/Jzs2Kn3R19fQmHb48",
  "https://maps.app.goo.gl/y3jYX9W7LDTMeGHr9",
  "https://maps.app.goo.gl/THFDv9Edxjg2RTe7A ",
  "https://maps.app.goo.gl/uKVHXxvdLKgdBCgo7",
  "https://maps.app.goo.gl/PPcG3fLr1rBiywuWA",
  "https://maps.app.goo.gl/aTREvs8NdjcynuR68",
  "https://maps.app.goo.gl/M1DbZVJfpcHMj8a57",
  "https://maps.app.goo.gl/7nVFSFkFTiqABPe86 ",
  "https://maps.app.goo.gl/9cHT4DtNm5qUJJmZ8",
  "https://maps.app.goo.gl/95h8dkypy3MTfk8v9",
  "https://maps.app.goo.gl/H9mmFPbFMmAFQtyc7",
  "https://maps.app.goo.gl/izsfpj5nsMih76si6",
  "https://maps.app.goo.gl/hk4QkxGdFXZi78tYA",
  "https://maps.app.goo.gl/yN8oZ9uzV3NaQ5yQ6",
  "https://maps.app.goo.gl/EGsD67RYXWDQyo1RA",
  "https://maps.app.goo.gl/7Q8Ki4XoRdaKiaLp8",
  "https://maps.app.goo.gl/TdJToujhx2SKd2GB8",
  "https://maps.app.goo.gl/MenM2RQHbchR5pEK7",
  "https://maps.app.goo.gl/Rm88xgqxCSCoBHeT7",
  "https://maps.app.goo.gl/K7XT9g64SM1VLwtJ6",
  "https://maps.app.goo.gl/iRvFrTajSTTLPsqe6",
  "https://maps.app.goo.gl/JU1VxQaCaSiyi3kn7",
];

export const BHAGWANPUR_2_MAP_OPTIONS = [
  "https://maps.app.goo.gl/jvZWZ56coPnvCED56",
  "https://maps.app.goo.gl/jvZWZ56coPnvCED56",
  "https://maps.app.goo.gl/55jLMhebjHe5Ma386",
  "https://maps.app.goo.gl/Kr5WdkBhsu5xn8gF9",
  "https://maps.app.goo.gl/aajfhexJMp12sQGR9",
  "https://maps.app.goo.gl/fvm5zcbWjSx28oj3A",
  "https://maps.app.goo.gl/bqH6YU1XA7ffSdvG8",
  "https://maps.app.goo.gl/QTtxNiyW7FKDxMSf8",
  "https://maps.app.goo.gl/NNnkyyYjP8aa8pY9A",
  "https://maps.app.goo.gl/DijZBV4tX7Yj1VXH7",
  "https://maps.app.goo.gl/GHYSeT3uYmGoGRMy9",
  "https://maps.app.goo.gl/CY1rEjA1NRaZ1YCn8",
  "https://maps.app.goo.gl/5DYcyYiHdkhvLDUF8",
  "https://maps.app.goo.gl/Gw6i47Eebv1eVZ1TA",
  "https://maps.app.goo.gl/qrYg25nyLkxmYhWB9",
  "https://maps.app.goo.gl/UqdEt5YkJLjbYDrn8",
  "https://maps.app.goo.gl/1tez5JiHw73Cvs419",
  "https://maps.app.goo.gl/Ckf9KoBXP5yhsJ9x8",
  "https://maps.app.goo.gl/VzzWyvjr1zvT9Zxa8",
  "https://maps.app.goo.gl/xC25VFVapXUCbJHs8",
  "https://maps.app.goo.gl/HQPrJctWPwuKXFTW9",
  "https://maps.app.goo.gl/HQPrJctWPwuKXFTW9",
  "https://maps.app.goo.gl/bPjkwoCUG1uCR8rX7",
  "https://maps.app.goo.gl/ME5pjq8toRbFxuhRA",
  "https://maps.app.goo.gl/HR9nB3QNb7R4BuF38",
  "https://maps.app.goo.gl/Y4Csna53yFVWSVDB9",
  "https://maps.app.goo.gl/4UgA4rXjYWveZyWx8",
  "https://maps.app.goo.gl/CAJ8mCentnDkGq418",
  "https://maps.app.goo.gl/Uk7GvLhTWAno8HR46",
  "https://maps.app.goo.gl/dp8B8WkMmndZdkW19",
  "https://maps.app.goo.gl/WEJSt3G2noWXmNfL9",
  "https://maps.app.goo.gl/Y8HpECEw3HXNmsyu6",
  "https://maps.app.goo.gl/khBnJMUBS9xkSxcq7",
  "https://maps.app.goo.gl/vvQejbVgMLKhEbxf8",
  "https://maps.app.goo.gl/vukoUaTA7tQn82Tj6",
  "https://maps.app.goo.gl/dxcxRVEpPhNfqZZi9",
  "https://maps.app.goo.gl/gxRnXkrc4BE97b9p7",
  "https://maps.app.goo.gl/KnZVbgZ5SZTeGmsv9",
  "https://maps.app.goo.gl/6fR1HMYBrBsHrYNU8",
  "https://maps.app.goo.gl/z3pNQRZtGMRrbqg8A",
  "https://maps.app.goo.gl/yMLJkcwcgNBuYqZ19",
  "https://maps.app.goo.gl/AcURXNkLhHMBhQJR8",
  "https://maps.app.goo.gl/Jw38Xgs6sYmmJDhSA",
  "https://maps.app.goo.gl/ccVcpe928hTmmfS48",
  "https://maps.app.goo.gl/MPu9z6ApboLT9bA66",
  "https://maps.app.goo.gl/EUAh31SHvjTBTXtZA",
  "https://maps.app.goo.gl/tmqmNNx1a9rNPaU26",
  "https://maps.app.goo.gl/tmqmNNx1a9rNPaU26",
  "https://maps.app.goo.gl/6xVGSE6nm8DwZH1s6",
  "https://maps.app.goo.gl/16k1EQa6jWHNL4RR7",
  "https://maps.app.goo.gl/GkTKAq1Wh1uLKdfE9",
  "https://maps.app.goo.gl/RgV5PDAvFHAqaMdaA",
  "https://maps.app.goo.gl/SL86vY3DJTwUyh546",
  "https://maps.app.goo.gl/4VzH48G6a9asaGDs7",
  "https://maps.app.goo.gl/1WgcFjHbXeyiPr9e7",
  "https://maps.app.goo.gl/n3QtVRHpaSHpqGah6",
  "https://maps.app.goo.gl/sz8vWw4mD9dSAXnh6",
  "https://maps.app.goo.gl/Xv4RH4m2EU65YB9z6",
  "https://maps.app.goo.gl/738Kdf2XoS7fNMBp7",
  "https://maps.app.goo.gl/xvq6orXwmSc1hWFeA",
  "https://maps.app.goo.gl/2rHfDWP52N7jse3f7",
  "https://maps.app.goo.gl/uq8fxFnCTn7Wr7as5",
  "https://maps.app.goo.gl/RHVGvxWyraQoHwvPA",
  "https://maps.app.goo.gl/Q9XVpRkof3vWwq2z5",
  "https://maps.app.goo.gl/RHVGvxWyraQoHwvPA",
  "https://maps.app.goo.gl/T7kQB1YnizDDVBjPA",
  "https://maps.app.goo.gl/4i9qEqcTCctKWhjE9",
  "https://maps.app.goo.gl/ppf2Qwpm5PRFSFVr6",
  "https://maps.app.goo.gl/zrZxjzBSWbVFAUHQ9",
  "https://maps.app.goo.gl/VcSHYswkWZw5AZpM8",
  "https://maps.app.goo.gl/1v6XnTXariBfee368",
  "https://maps.app.goo.gl/pkxMuxcXGZCquH8b8",
  "https://maps.app.goo.gl/7pe1kdgd7QpdK4ry5",
  "https://maps.app.goo.gl/17C5f1RQ53pGTbPE6",
  "https://maps.app.goo.gl/Tzzauf7zbF8da66K9",
  "https://maps.app.goo.gl/6aM97AMNoBxqWmhs5",
  "https://maps.app.goo.gl/VQ8LfUzokNWCdNyq6",
  "https://maps.app.goo.gl/a9e2dtTi9vs5uGBUA",
  "https://maps.app.goo.gl/b8zR8V9bQFHfDjqZ9",
  "https://maps.app.goo.gl/3uHeGpJi67k5y1yo8",
  "https://maps.app.goo.gl/NV6Szw3fEMZKte3A6",
  "https://maps.app.goo.gl/4XH1WeWsGLfb3StD9",
  "https://maps.app.goo.gl/eiH7YskajaCPw7EP8",
  "https://maps.app.goo.gl/pEh1ZCTTNcDHFKNs7",
  "https://maps.app.goo.gl/pEh1ZCTTNcDHFKNs7",
  "https://maps.app.goo.gl/7k1fB6LRAggKyosi9",
  "https://maps.app.goo.gl/V5EPEAENvdYs8vS57",
  "https://maps.app.goo.gl/2GoHRVbWESt2aGKD9",
  "https://maps.app.goo.gl/B4mDZGP1cC4UbLXi8",
  "https://maps.app.goo.gl/U3jo6wmhqvnAEJLN6",
  "https://maps.app.goo.gl/91nCbLxSK8cDDYBs7",
  "https://maps.app.goo.gl/tU8HtWRB6pjKEmzHA",
  "https://maps.app.goo.gl/3hfrLhXkAT2EvLEL9",
  "https://maps.app.goo.gl/YpuXPNo2o89n6qoF7",
  "https://maps.app.goo.gl/SEGhuAvSMhhsZdGF8",
  "https://maps.app.goo.gl/SaNo7BRx3jhqtsDa8",
  "https://maps.app.goo.gl/4c2qAkAcNm5jDv7w9",
  "https://maps.app.goo.gl/4c2qAkAcNm5jDv7w9",
  "https://maps.app.goo.gl/AkSfQnB217cQ9v9K8",
  "https://maps.app.goo.gl/NWps3nPWnBRt9tKi8",
  "https://maps.app.goo.gl/FFCyspQZEXYm78DH9",
  "https://maps.app.goo.gl/pjJo35oapC1Y39qMA",
  "https://maps.app.goo.gl/BAtZdDi1gCbPGya89",
  "https://maps.app.goo.gl/FTSPBMmReFTjvbnf7",
  "https://maps.app.goo.gl/UUjbhqHWPA36VigX9",
  "https://maps.app.goo.gl/6DiJM1oUwAKF5Soi7",
  "https://maps.app.goo.gl/PiZTruT7EoLRUcrM8",
  "https://maps.app.goo.gl/EPvzDgDX3yPahbZH9",
  "https://maps.app.goo.gl/G9TQNt4ZDJXrNe38A",
  "https://maps.app.goo.gl/qmn8z9jbvoYHtPVA7",
  "https://maps.app.goo.gl/5sXxHk55k2tCZ11L7",
  "https://maps.app.goo.gl/TqefvhY24gJYajeN9",
  "https://maps.app.goo.gl/EPFirwsh8hJdVbYo6",
  "https://maps.app.goo.gl/3JarAy1mU7egUj9x5",
  "https://maps.app.goo.gl/zyDZXmnJByxmuehHA",
  "https://maps.app.goo.gl/j3zhinTdyD7SPac39",
  "https://maps.app.goo.gl/oJs6VWZcAuS1P4T78",
  "https://maps.app.goo.gl/SZ7u15iTTeZH32pYA",
  "https://maps.app.goo.gl/SZ7u15iTTeZH32pYA",
  "https://maps.app.goo.gl/h1D4Rz6dHR167Gxx8",
  "https://maps.app.goo.gl/h1D4Rz6dHR167Gxx8",
  "https://maps.app.goo.gl/9fuyjGeK4QRyDemF8",
  "https://maps.app.goo.gl/x9aRusr5RuacjU3H7",
  "https://maps.app.goo.gl/oaF3uBV6AtMjBQGn9",
  "https://maps.app.goo.gl/T1y5n5iVVUbdh2mRA",
  "https://maps.app.goo.gl/WoqS1CD4xjaoWGodA",
  "https://maps.app.goo.gl/F79mNbqxZsgUMGLL6",
  "https://maps.app.goo.gl/NS16Ahf83VfygxrF8",
  "https://maps.app.goo.gl/hHRrEFzbAQ77L7RC7",
  "https://maps.app.goo.gl/hHRrEFzbAQ77L7RC7",
  "https://maps.app.goo.gl/UUsyBtCbWcYhNBXM9",
  "https://maps.app.goo.gl/FEMC4Q25ZniZJuu6A",
  "https://maps.app.goo.gl/tc8Yo78uhwZ94XEu7",
  "https://maps.app.goo.gl/3MttzA7FhMQGqKLH9",
  "https://maps.app.goo.gl/t82qHwmntLYt6MPr8",
  "https://maps.app.goo.gl/4FhQLmRY2GiWeRMk7",
  "https://maps.app.goo.gl/4FhQLmRY2GiWeRMk7",
  "https://maps.app.goo.gl/jaeZqQRpvMSjV1WUA",
  "https://maps.app.goo.gl/nXwhd2EcKpzLMTQj9",
  "https://maps.app.goo.gl/nXwhd2EcKpzLMTQj9",
];
