export const BHAGWANPUR_1_OPTIONS = [
  "1 - Barbhagwanpur Primary School",
  "2 - Barbhagwanpur Primary School",
  "3 - Banamalipur Primary School",
  "4 - Banamalipur Sishu Siksha Kendra",
  "5 - Nunhanda Kshudiram M.S.K",
  "6 - Nunhanda Palli Vidyapith",
  "7 - Nunhanda Palli Vidyapith",
  "8 - Talda Primary School",
  "9 - Chinyaandulia Board Prathamik vidyalay",
  "10 - Shyamchak Primary School",
  "11 - Srikantapur Prathamik vidyalay",
  "12 - Kulberia Prathamik vidyalay",
  "13 - Kulberia Prathamik vidyalay",
  "14 - Simulia s.K.u.s. Limited",
  "15 - Baman Simulia Prathamik vidyalay",
  "16 - Bhimeswari Uchha sikshayatan",
  "17 - Bhimeswari Balika vidyapith",
  "18 - Bartan Special Primary School",
  "19 - Bartan Special Primary School",
  "20 - Unal Primary School",
  "21 - Katgechhia Primary School",
  "22 - Kishorpur Sridurga Prathamik vidyalay",
  "23 - Rampur Primary School",
  "24 - Illashpur Stateplane Prathamik vidyalaya",
  "25 - Illashpur Harijan Board Prathamik vidyalaya",
  "26 - Barbasudebpur Primary School",
  "27 - Paikbheri Shyamsundar Primary School",
  "28 - Kuber Dutta Veri Sishu Siksha Kendra",
  "29 - Kalurbheri Prathamik vidyalay",
  "30 - Kalurbheri Prathamik vidyalay",
  "31 - Dakshin Bishnupur Prathamik vidyalaya",
  "32 - Uttar Bishnupur Primary School",
  "33 - Bachhipur Sishu Siksha Kendra",
  "34 - Bachhipur Atyayik Prathamik Vidyalaya",
  "35 - Bhagwanpur Highschool",
  "36 - Bhagwanpur State Plan Prathamik vidyalay",
  "37 - Durgapur Board Prathamik vidyalay",
  "38 - Jalibarh Prymary School",
  "39 - Paschim Ghoshpur Primary School",
  "40 - Shibarampur Atyaik Pry.School",
  "41 - Uttar Bhagwanpur Nabarun vidyapith",
  "42 - Khaga Board Prathamik vidyalaya",
  "43 - Babia Prathamik vidyalaya",
  "44 - Sarangapur Prathamik Vidyalaya",
  "45 - Abasberia Adarsha vidyapith(highschooll)",
  "46 - Abasberia Board Primary School",
  "47 - Baraibar Board Prathamik vidyalay",
  "48 - Baraibarh New Pry.School",
  "49 - Jagamohanpur Primary School",
  "50 - Lohabar Prathamik vidyalaya",
  "51 - Paschim Sarberia Ojuda Madhyamik Siksha Kendra",
  "52 - Sarberia Uchha Prathamik Maktab vidyalaya",
  "53 - Sarberia Board Prathamik vidyalaya",
  "54 - Bhabanichak Prathamik vidyalaya",
  "55 - Hinchageria Stateplan Primary School",
  "56 - Hinchageria Stateplan Primary School",
  "57 - Hinchageria Special cader Primary School",
  "58 - Hinchageria Special cader Primary School",
  "59 - Narayandari Natun Prathamik vidyalaya",
  "60 - Narayandari Board Primary School",
  "61 - Bajaberia Prathamik vidyalaya",
  "62 - Narayandari Barbajaberia Natun Primary vidyalaya",
  "63 - Tethibari State Plan Primary School",
  "64 - Kaptyabari Board (Atyayik) Prathamik vidyalaya",
  "65 - Dakshin Kaptyabari Bishnuhari Primary School",
  "66 - Kajlagar M.S.B.C.M. Highschool",
  "67 - Kajlagar Uchha Prathamik vidyalaya",
  "68 - Mirjapur Pry.School",
  "69 - Sujamutha-Manoharpur Uchcha Prathamik vidyalaya",
  "70 - Dayalchak Primary vidyalaya",
  "71 - Purbaradhapur Jitnarayan Prathamik vidyalaya",
  "72 - Purbaradhapur Jitnarayan Prathamik vidyalaya",
  "73 - Shukrullapur Board Prathamik vidyalay",
  "74 - Shukrullapur Atyayik Uchcha Prathamik vidyalaya",
  "75 - Shukrullapur Atyayik Uchcha Prathamik vidyalaya",
  "76 - Deuribar Kiranprabha vidyamandir",
  "77 - Ashutia Sarojini vidyapith (Highschooll)",
  "78 - Ashutia Sarojini vidyapith (Highschooll)",
  "79 - Balaramchak Primary School",
  "80 - Shyamchak Radhakrishna Uchcha Prathamik vidyalaya",
  "81 - Gumkia Shyamchak Atyaik Primary School",
  "82 - Charabar Girls Prathamik vidyalaya",
  "83 - Shyamchak Radhakrishna Uchcha Prathamik vidyalaya",
  "84 - Charabar Girls Highschool",
  "85 - Charabar Girls Highschool",
  "86 - Kalaberia Primary School (Daspara)",
  "87 - Kalaberia Primary School (Daspara)",
  "88 - Kotbarh Board Primary School",
  "89 - Kotbarh vidyasundari Primary School",
  "90 - Chowdunia Pry.School",
  "91 - Dalbar Ramnarayan Prathamik vidyalaya",
  "92 - Kotbarh Maktab Prathamik vidyalay",
  "93 - Kotbarh vidyasundari Primary School",
  "94 - Kotbarh Maktab Prathamik vidyalay",
];

export const BHAGWANPUR_2_OPTIONS = [
  "95 - Ururi Primary School",
  "96 - Ururi Primary School",
  "97 - Chinadanri Primary School",
  "98 - Bahadurpur 3No Primary School",
  "99 - Bahadurpur I.C.J.C.K.",
  "100 - Bahadurpur 2No Primary School",
  "101 - Bahadurpur Purbapara SSK",
  "102 - Bahadurpur Desapran Sikshaniketan Highschool",
  "103 - Iswarpur Junior Basic School",
  "104 - Sankhadiha Primary School",
  "105 - Machnan Primary School",
  "106 - Madhabpur Indranarayan Highschooll",
  "107 - Haripur Highschool",
  "108 - Radhapur Prabin Primary School",
  "109 - Radhapur Muslim Palli Primary School",
  "110 - Dakshin Radhapur Haracharan SSK",
  "111 - Kismat Khatiyal Special Kyader Primary School",
  "112 - Barbaria Hazra vidyapith",
  "113 - Simuldanri Primary School",
  "114 - Khatial Primary School",
  "115 - Basudebberia Primary School (Bashuli Bazar)",
  "116 - Basudebberia Primary School (Bashuli Bazar)",
  "117 - Basudebberia Hariparaprimary school",
  "118 - Uttar Pathar Beria Primary School",
  "119 - Manikjore Stateplyan Primary School",
  "120 - Manikjore Harijan Palli Primary School",
  "121 - Konchak Pry.School",
  "122 - Dakshin Patharberia Anandamoyee Balika vidyalay",
  "123 - Dakshin Pathar Beria Primary School",
  "124 - Khantmari Biswanathpur Primary School",
  "125 - Laudighi Primary School",
  "126 - Neturia Primary School",
  "127 - Champainagar S.C. Hihg School",
  "128 - Udbadal Maa Basanti SSK",
  "175 - Pachahari Primary School",
  "176 - Purbahari SSK",
  "177 - Dubai Rasiknagar vivekananda Highschool (Purbangsha)",
  "178 - Dubai Primary School",
  "179 - Maishali Primary School",
  "180 - Jiakhali Primary School",
  "181 - Uttar Khamar Primary School",
  "182 - Alukaranbar Pry.School",
  "183 - Panchbajari Primary School",
  "184 - Purbabajari Primary School",
  "185 - Teghari Primary School",
  "186 - Bamanbar Primary School",
  "187 - Kotmukha Primary School",
  "188 - Kotmukha Primary School",
  "189 - Jashibar Primary School",
  "190 - Jashibar Primary School",
  "191 - Kunjapara Primary School",
  "192 - Itaberia State Plan Primary School",
  "193 - Itaberia Primary School,(Bazar Said)Purbangsha",
  "194 - Asfhakulla SSK",
  "195 - Haridrachak Primary School",
  "196 - Kamal Nayanbar Primary School",
  "197 - Uttardigha Primary School",
  "198 - Dhaipukuria Primary School",
  "199 - Dhaipukuria State Plan pry.School",
  "200 - Naruabila Junior highschool",
  "201 - Madhyabila Primary School",
  "202 - Parulia Primary School",
  "203 - Arjunnagar 2No Primary School (Paschimangsha)",
  "204 - Arjunnagar MSK",
  "205 - Arjunnagar 2No Primary School (Paschimangsha)",
  "206 - Arjunnagar 1 No Prathamik vidyalay",
  "207 - Ratnajore Primary School",
  "208 - Khejur Gachhia Bhoslageria Primary School",
  "209 - Kalmichhabar Primary School",
  "210 - Analberia Primary School",
  "211 - Nijnarua Primary School",
  "212 - Ichchhabari highschool",
  "213 - Chingra Primary School",
  "214 - Janumanu Primary vidyalay",
  "215 - Kismat Patna Primary School",
  "216 - Dumurdari Raghunath high school",
  "217 - Padmatamli Primary School",
  "218 - Padmatamli Harijan Palli Pry.School",
  "219 - Bayenda Board Primary School",
  "220 - Dakshin Bayenda Pry. School",
  "221 - Ichchhapur Primary School",
  "222 - Panchghari Primary School",
  "223 - Garabar Primary School",
  "224 - Keshaidighi Primary School",
  "225 - Keshaidighi Primary School",
  "226 - Khanjadapur Rajbangshi Primary School",
  "227 - Khanjadapur SSK",
  "228 - Paschim Kalagechhiya Primary vidyalay",
  "229 - Mugberia Gangadhar High School",
  "230 - Bhupatinagar Kanya vidyalay",
  "231 - Bhupatinagar Primary School (Pradhan Para) Purbangsha",
  "232 - Bhupatinagar parya para s.s.k",
  "233 - Angarberia Primary School",
  "234 - Raghunathchak Junior Highschool",
  "235 - Jiagodi SSK",
  "236 - Mulda Primary School",
  "237 - Kayemgeria D,M,Highschooll (Purbangsha)",
  "238 - Kayemgeria D,M,Highschooll ()",
  "239 - Uttar Baroj Primary School",
  "240 - Dakshin Baroj 2nd Khanda Primary School",
  "241 - Shimulbari Primary School",
  "242 - Diha Shimulia Primary School",
  "243 - Kayemgeria Primary School",
  "244 - Uttar Nischinta Primary School",
  "245 - Dakshin Mahishda Primary School",
  "246 - Dighadanri Primary School",
  "247 - Uttar Bijay Nagar Primary School",
  "248 - Dakshin Bijaynagar S.S.K",
  "249 - Paunshi Annapurna Nimna Buniadi vidyalay",
  "250 - Pausi Baikuntha Smriti Milani Vidyamandir",
  "251 - Chirakuti Primary School",
  "252 - Gholbagda Primary School",
  "253 - Kutubuddinpur Primary School",
  "254 - Madhakhali Primary School",
  "255 - Garania Primary School",
  "256 - Gobindachak Special Kyader Primary school",
  "257 - Sadulyachak Primary School",
  "258 - Ikshu Patrika Primary School(Purbangsha)",
  "259 - Ikshu Patrika Primary School(Purbangsha)",
  "260 - Jukhiasitadighispecial Kyader Primaryschool(Purbangsha)",
  "261 - Jukhiasitadighispecial Kyader Primaryschool(Purbangsha)",
  "262 - Jukhia Ramhari Primary School",
  "263 - Sita Dighi Primary School",
  "264 - Bamunia Primary School",
  "265 - Jukhia K.N.Banimandir (High School)",
  "266 - Dhelua Primary School",
  "267 - Nelua Primary School",
  "268 - Gopalchak SSK",
  "269 - Ramchak Primary School (Purbangsha)",
  "270 - Ramchak Primary School (Purbangsha)",
  "271 - Ramchak new Primary School",
  "272 - Biribari Primary School",
  "273 - Kantapukuria New Primary School",
  "274 - Kantapukhuria Board Pry.School",
  "275 - Baghadanri high School",
  "276 - Baghadanri Primary School",
  "277 - Baghadanri Primary School",
  "278 - Ektarpur I.C.D.S. Center",
  "279 - Ektarpur Pry. School(Paschimangsha) PART -  1",
  "280 - Ektarpur Primary School(Paschimangsha)Part  - 2",
];

export const PATASHPUR_2_OPTIONS = [
  "129 - Khetrapal Chakbhogi Atyayik Prathamik vidyalay",
  "130 - Khetrapal Chakbhogi Atyayik Prathamik vidyalay",
  "131 - Chakbhogi Prathamik vidyalay",
  "132 - Ballyagobindapur Board Pry.School",
  "133 - Ballyagobindapur Balika Vidyalaya",
  "134 - Ballyagobindapur Gnankarma Vidyapith(Uttarngsha)",
  "135 - Balyagobindapur gankarma vidyapith (Dakshinangsha)",
  "136 - Chandankhali Prathamik vidyalay",
  "137 - Madanmohanpur Draupadi Sundari Prathamik vidyalay",
  "138 - Panchagram Sikshaniketan",
  "139 - Uttar Itaberia Prathamik vidyalay",
  "140 - Hakimpur Prathamik vidyalay",
  "141 - Budhijore Prathamik vidyalay",
  "142 - Bhubanmangalpur Prathamik vidyalay",
  "143 - Saradabarh Srihari Vidyapith",
  "144 - Pania Saradabar Ramkrishna Sikshasadan",
  "145 - Mathura Prathamik vidyalay (Uttarangsha)",
  "146 - Mathura Prathamik vidyalay (Dakshinangsha)",
  "147 - Tahalia Deulbar Prathamik vidyalay",
  "148 - Mangraj Prathamik vidyalay",
  "149 - Lalua Chakrashul Board Prathamik vidyalay",
  "150 - Lalua Adarsha Prathamik Bidyalay (East)",
  "151 - Lalua Adarsha Prathamik vidyalay",
  "152 - Chakpadu Prathamik vidyalay",
  "153 - Argoal Nankar Prathamik vidyalay",
  "154 - Argoal Board Prathamik vidyalay",
  "155 - Jabda vidyasagar vidyapith (Purbangsha)",
  "156 - Jabda vidyasagar vidyapith ( Paschimangsha)",
  "157 - Dakshin lawa Pry.School",
  "158 - Kakhuria Bapuji Prathamik vidyalay",
  "159 - Paschim Lawa SSK",
  "160 - Mangalchak Saraswati Prathamik vidyalay",
  "161 - Khatibarh Haripur Jr. High School",
  "162 - Nekursini Krishishilpa Siksha Sadan(Highschooll)",
  "163 - Taniabila Prathamik vidyalay",
  "164 - Babuidanri Prathamik vidyalay",
  "165 - Sinyari Harijan Nimna Buniadi vidyalay",
  "166 - Braja Ballavpur Pry. School",
  "167 - Samaspur Bishnupriya Balika vidyalay(Ju:high School)",
  "168 - Uttar Sandalpur Free Prathamik vidyalay",
  "169 - Dakshin Sandalpur Prathamik vidyalay",
  "170 - Ichchhabari Kunjabihari Special Prathamik vidyalay",
  "171 - Kourmoishali Pry.School",
  "172 - Paninala Prathamik Vidyalaya",
  "173 - Satshatamal Special Prathamik vidyalay",
  "174 - Satshatamal Board Prathamik vidyalay",
];
