export const EGRA_1_OPTIONS = [
  "54 - Nijdanta Prathamik vidyalay ",
  "55 - Amipara S.S.K ",
  "56 - Krishnapur S.S,K ",
  "57 - Rukminipur Kanai Lal vidyapith ",
  "58 - Rukminipur Primary School ",
  "59 - Saharda Prathamik vidyalay ",
  "60 - Sultanpur S.S.K ",
  "61 - Uttar Erenda Prathamik vidyalay ",
  "62 - Erenda Highschool ",
  "63 - Erenda Highschool ",
  "64 - Shushunia Primary School ",
  "65 - Erenda Prathamik vidyalay ",
  "66 - Uttar Panthai Prathamik vidyalay ",
  "67 - Rajendrachak Prathamik vidyalay ",
  "68 - Rajendrachak Prathamik vidyalay ",
  "69 - Urijalkar S.S.K Room - 1",
  "70 - Onsarisha S.S.K. ",
  "71 - Keutgeria vidyasagar Highschool ",
  "72 - Ultabad S.S.K. ",
  "73 - Hurkuchia Prathamik vidyalay ",
  "74 - Shilampur 1 No Primary School ",
  "75 - Shilampur No.2 Primary School ",
  "76 - Ultabad Shilampur Nilakantha Primary School ",
  "77 - Shyampur Ashram Uchcha Prathamik vidyalay ",
  "78 - Bidurpur Prathamik vidyalay ",
  "78A - Bidurpur Prathamik vidyalay ",
  "79 - Sahapur Prathamik vidyalay ",
  "80 - Urdhabpur jhatucharan Prathamik vidyalay ",
  "81 - Daudpur Binapani Uchcha Prathamik vidyalay ",
  "82 - Daudpur Binapani Uchcha Prathamik vidyalay ",
  "83 - Uttar Daudpur Prathamik vidyalay ",
  "84 - Daudpur Samabay Krishi Unnayan Samity ",
  "85 - Tajpur Sammilita Atyayik Prathamik vidyalay ",
  "86 - Tajpur Nimna Buniyadi Prathamik vidyalay ",
  "87 - Tajpur vidyasagar Primary School ",
  "88 - Nimakbar Sitalasebak shantamoni Prathamik vidyalay (Uttarangsha)",
  "89 - Nimakbar Sitalasebak shantamoni Prathamik vidyalay ",
  "90 - Kamalpur Primary vidyalay ",
  "91 - Kamalpur Primary vidyalay ",
  "92 - Bhatda Gandhi Maydan S.S.K ",
  "93 - Bhatda Board Prathamik vidyalay ",
  "94 - Bhatda Gadadhar Primary School ",
  "95 - Baincha Prathamik vidyalay ",
  "96 - Baincha Nazrul S.S.K ",
  "97 - Farakpara S.S.K ",
  "98 - Balighai Fakirdas Highschool ",
  "99 - Tolakana Primary School ",
  "100 - Mallikpur Primary School ",
  "101 - Uttar Baranidhi S.S.K ",
  "102 - Dakshin baranidhi basanta s.s.k ",
  "103 - Tentuliagiri Prathamik Vidyalaya ",
  "104 - Tentuliagiri S.S.K. ",
  "105 - Nayapara Primary School ",
  "106 - Balighai Sikshasadan ",
  "107 - Dakshinchak Srikrishna Board Prathamik vidyalay ",
  "108 - Dakshinchak Highschool ",
  "109 - Khejurda Tentuliagiri Nazrul Madhyamik Siksha Kendra ",
  "110 - Khejurda Prathamik Vidyalay ",
  "111 - Daudpur Prathamik vidyalay ",
  "112 - Alipur Sukanta S.S.K ",
  "113 - Ariapota Prathamik vidyalay ",
  "240 - Khurutia Nimnabuniadi vidyalay ",
  "241 - Khurutia Nimnabuniadi vidyalay ",
  "242 - Teghari Primary School ",
  "243 - Lalpur Prathamik vidyalay ",
  "244 - Paniparul Mukteswar Uchhavidyalay ",
  "245 - Paniparul Mukteswar Uchhavidyalay ",
  "246 - Baincha Primary School ",
  "247 - Pashcim Paniparul Prathamik vidyalay ",
  "248 - Debidaspur Gandhi Harijan Primary School ",
  "249 - Debidaspur Gandhi Harijan Primary School ",
  "250 - Kapasda Shitala Primary School ",
  "251 - Kapasda Shitala Primary School ",
  "252 - Chirkunpada Primary School ",
  "253 - Chandalda Narayani Primary School ",
  "254 - Sarisha Primary School ",
  "255 - Aranga Mahendra Prathamik vidyalay ",
  "256 - Aranga Vivekananda S.S.K ",
  "257 - Paniparul Primary School ",
  "258 - Lalpur Mukteswar Girls Haighschool ",
  "259 - Kultikri Prahallad vidyapith (Singha Para) ",
  "260 - Kultikri Harekrishna prathamik vidyalay ",
  "261 - Kultikri Harekrishna prathamik vidyalay ",
  "262 - Khagada Pallishri Highschool ",
  "263 - Khagda Prathamik vidyalay ",
  "264 - Chhotokhagda Primary School ",
  "265 - Dubda Deshapran Birendra vidyapith ",
  "266 - Dubda Deshapran Birendra vidyapith ",
  "267 - Dubda Deshapran Prathamik Bidyalay ",
  "268 - Dubda 2No Uttam Charan Prathamik vidyalay ",
  "269 - Dubda Saradamoni Harizon Prathamik Vidyalay ",
  "270 - Dubda 1No Prathamik vidyalay ",
  "271 - Dubda Bani vidyapith ",
  "272 - Asti Primary School ",
  "273 - Geria Prathamik vidyalay ",
  "274 - Gholdubda Prathamik vidyalay ",
  "275 - Ghol Dubda S.S.K ",
  "276 - Shnakapada Prathamik vidyalay ",
  "277 - Shnakapada Prathamik vidyalay ",
  "278 - Rasulpur Dakshinbar Prathamik vidyalay ",
  "279 - Sanbheri Kalu Roy Primary School ",
  "280 - Chhoto Rasulpur Prathamik vidyalay (Jelepara) ",
  "281 - Baranalgeria jogendra Primary vidyalay(Maiti Para) ",
  "282 - Baranalgeria New Primary School ",
  "283 - Atbati Annapurna Bidyamandir ",
  "284 - Chhotonalgeria Primary vidyalay(Uttarangsha)Haripara ",
  "285 - Naskarpur Bhubaneswari Prathamik vidyalay ",
  "286 - Ganeswarpur Prathamik vidyalay (Giri Para) ",
  "287 - Ganeswarpur Bhagbat Prathamik vidyalay (Payrapara) ",
  "288 - Egra Patna Prathamik vidyalay (Karapara) ",
  "289 - Mahespur Ramakanta Prathamik vidyalay (Maitipara) ",
  "290 - Beta Hat Primary School ",
  "291 - Shyamharibar Samabay Adarsha vidyalay ",
  "292 - ShyamhariBar Primary School ",
  "293 - Shyamharibar Tripalli Primary School ",
  "294 - Basudebpur Sabuj Sanggha (Pathagar) ",
  "295 - Uttar Basudebpur Primary School ",
  "296 - Basudebpur Haripriya Institiution ",
  "297 - Basudevpur Primary School ",
  "298 - Jinandapur Primary School ",
  "299 - Bhabanichak Highschool (Uchcha Madhyamik) ",
  "300 - Bhabanichak Raghunath Primary School ",
  "301 - Basudebpur Kiranmaye Primary School ",
  "302 - Naskarpur Basudebpur Matilal Prathamik vidyalay ",
  "303 - Chirulia Srinathchandra vidyapith ",
  "304 - Dulalpur Prathamik vidyalay ",
  "305 - Dulalpur Benepukur S.S.K ",
  "306 - Bachchhipur Primary School ",
  "307 - Motaghat S.S.K(Patra Para) ",
];

export const EGRA_2_OPTIONS = [
  "1 - Teantulia Shararang N,N,High School ",
  "2 - Teantulia Shararang N,N,High School ",
  "3 - Shararang Prathamik Vidyalay ",
  "4 - Tentulia Primary School ",
  "5 - Kaurda Prathamik vidyalay ",
  "6 - Kaurda Prathamik vidyalay ",
  "7 - Barida Anganwadi Kendra (No.-7) Room - 1",
  "8 - Barida Patna Prathamik vidyalay ",
  "9 - Barida Prathamik vidyalay ",
  "10 - Barida Prathamik vidyalay ",
  "11 - Barttana Harisabha Prathamik vidyalay ",
  "12 - Bartana S.S.K ",
  "13 - Barttana Board Prathamik vidyalay ",
  "14 - Khalina Prathamik vidyalay ",
  "15 - Khalina Prathamik vidyalay ",
  "16 - Madhabpur Primary School ",
  "17 - Kalyanpur S.S.K ",
  "18 - Bayespur Prathamik vidyalay ",
  "19 - Bataspur Primary School ",
  "20 - Dalaluya Prathamik vidyalay Room- 1 ",
  "21 - Comunity Centre (Ulipur, Ward No. 2) Room - 1",
  "22 - Dalaluya Prathamik vidyalay Room-2 ",
  "23 - Aluya Prathamik vidyalay ",
  "24 - Bangshidharpur S.S.K ",
  "25 - Kasba Egra Prathamik Vidyalaya Room - 1",
  "26 - Egra Swarnamayee Girls High School ",
  "27 - Egra J L High School Room-2 ",
  "28 - Egra J L High School Room-2 ",
  "29 - Egra J L High School Room-3 ",
  "30 - Purushottampur Prathamik vidyalay ",
  "31 - Purushottampur Prathamik vidyalay ",
  "32 - Purusottampur S.S.K ",
  "33 - Purusottampur Community Hall ",
  "34 - Aklabad Prathamik vidyalay ",
  "35 - Egara S,S,B.College ",
  "36 - Egara S,S,B.College ",
  "37 - Jagannathapur Pallimangal Prathamik vidyalay ",
  "38 - Jagannathapur Pallimangal Prathamik vidyalay ",
  "39 - Adalabad Bhagabati Special Pra: School ",
  "40 - Adalabad Bhagabati Special Pra: School ",
  "41 - Comunity Centre (Kasba Egra, Ward No. 13) Room - 1",
  "42 - Kasba Egra Community Hall (Ward No. 12) Room - 2",
  "43 - Kashba Junior Basic School (Purbangsha) ",
  "44 - Kashba Junior Basic School (Purbangsha) ",
  "45 - Kashba Shitala Prathamik vidyalay ",
  "46 - Kashba Shitala Prathamik vidyalay ",
  "47 - Kainthor Ramchandrapur K.P. High School ",
  "48 - Kismat Ghatuia Mahendra Primary School ",
  "49 - Harichak Prathamik vidyalay ",
  "50 - Erendabar Primary School ",
  "51 - Errendabar SSK ",
  "52 - Mahabishra Balaram Primary School ",
  "53 - Mahabishra I.C.D.S Centre ",
  "114 - Kashimpur Primary School ",
  "115 - Ailan Primary School ",
  "116 - Baronihari Primary School Room-1 ",
  "117 - Baranihari Upper Primary School ",
  "118 - Ramkrishnapur S.S.K ",
  "119 - Sannihari Prathamik vidyalay ",
  "120 - Chhatri Vivekananda vidyabhaban (Paschimangsha) ",
  "121 - Chhatri Vivekananda vidyabhaban (Paschimangsha) ",
  "122 - Chhatri Harijan Primary School ",
  "123 - Chhatri Harijan Primary School ",
  "124 - Chhatri Nilkantha S.S.K ",
  "125 - Chhatri 2No,Prahaladchandra Primary School(Purbangsha) ",
  "126 - Chhatri 2No,Prahaladchandra Primary School(Purbangsha) ",
  "127 - Rasan Chalkbandi Primary vidyalay ",
  "128 - Rasan Chalkbandi Primary vidyalay ",
  "129 - Rasan Jagannath Primary School ",
  "130 - Rasan Jagannath Primary School ",
  "131 - Kudi proper Primary School ",
  "132 - Kudi proper Primary School ",
  "133 - Naraharipur Prathamik Vidyalay ",
  "134 - Kamardiha Prathamik School ",
  "135 - Benachakri Primary School ",
  "136 - Telami Prathamik vidyalay ",
  "137 - Hamarjita Prathamik vidyalay ",
  "138 - Satkhanda Prathamik Vidyalay ",
  "139 - Jerthan 1 No Prathamik School ",
  "140 - Jerthan 1 No Prathamik School ",
  "141 - Jarthan Gayaprasad vidyapith ",
  "142 - Jerthan Purba S.S.K ",
  "143 - Jarthan Gayaprasad vidyapith ",
  "144 - Jerthan 2 No Prathamik vidyalay ",
  "145 - Kiya Prathamik vidyalay ",
  "146 - Kiya S.S.k ",
  "147 - Dakshin Asda Prathamik vidyalay ",
  "148 - Alangiri Prathamik vidyalay ",
  "149 - Alangiri Radhabinod vidyapith ",
  "150 - Alangiri Radhabinod vidyapith ",
  "151 - Alangiri Pitambar Nabatirtha Primary School ",
  "152 - Alangiri S.S.K ",
  "153 - Panchrol Special Primary School (Dakshinangsha) ",
  "154 - Panchrol Special Primary School (Uttarangsha) ",
  "155 - Panchrol Special Primary School (Uttarangsha) ",
  "156 - Panchrol Board Primary School ",
  "157 - Panchrol Higher Secondary School (Paschimangsha) ",
  "158 - Panchrol Higher Secondary School (Paschimangsha) ",
  "159 - Rayda Prathamik vidyalay ",
  "160 - Bilbara S.S.K ",
  "161 - Baya Prathamik vidyalay ",
  "162 - Kalyanpur Prathamik vidyalay ",
  "163 - Dhusurda Primary School ",
  "164 - Bagmari Prathamik vidyalay ",
  "165 - Bagmari Prathamik vidyalay ",
  "166 - Gahabi Prathamik vidyalay ",
  "167 - Aruya S.S.K ",
  "168 - Kashbagola 1No Prathamik vidyalay ",
  "169 - Kashbagola 1No Prathamik vidyalay ",
  "170 - Kasbagola F,O, B, Highmadrasa ",
  "171 - Kasbagola F,O, B, Highmadrasa ",
  "172 - Kashbagola 2No Primary vidyalay ",
  "173 - Kashbagola 2No Primary vidyalay ",
  "174 - Purushottampur Primary School ",
  "175 - Malida Primary School ",
  "176 - Telami Highschool ",
  "177 - GopinathpurS.S.K ",
  "178 - Khodkul Primary School ",
  "179 - Ranisai Prathamik vidyalay ",
  "180 - Sahara High School ",
  "181 - Alipur Primary School ",
  "182 - Sahara Pallishri Primary School ",
  "183 - Satkania Harijan Primary School ",
  "184 - Dakshin Shipur Primary School ",
  "185 - Shipur Keshabeswar High School ",
  "186 - Sinduria Kripasindhu Primary School ",
  "187 - Dolbard Shunia Prathamik Vidyalay ",
  "188 - Harihar Shunia Primary School ",
  "189 - Tahalia Ramkrishna Smriti Prathamik vidyalay ",
  "190 - Pandua S.S.k ",
  "191 - Chorpalia Shri shri Basanti Vidyapith ",
  "192 - Chorpalia Primary School ",
  "193 - Negua Sundar Narayan High School ",
  "194 - Ramchandrapur Prathamik vidyalay ",
  "195 - Shikrachakdai Prathamik Vidyalay ",
  "196 - Amdai Pachim Pry. School ",
  "197 - Aamdai Kaderia Primary School ",
  "198 - Aamdai Kaderia Primary School ",
  "199 - Khalshutia Prathamik vidyalay ",
  "200 - Khalshutia Prathamik vidyalay ",
  "201 - Purunda Sarbamangala Primary School (Uttarangsha) ",
  "202 - Purunda Sarbamangala Primary School (Uttarangsha) ",
  "203 - Mirjapur Primary School ",
  "204 - Barada Magunicharan Junior Basic School ",
  "205 - Barada Magunicharan Junior Basic School ",
  "206 - Barada Magunicharan junior high school ",
  "207 - Solpatia Prathamik vidyalay ",
  "208 - Amadpur Primary School ",
  "209 - Akandi Junior Basic School ",
  "210 - Bhatshalia Prathamik vidyalay ",
  "211 - Negua R B C Pathshala ",
  "212 - Nutiberh Primary School ",
  "213 - Radhapur Prathamik vidyalay ",
  "214 - Jagulia Primary School ",
  "215 - Arjuni Prathamik vidyalay ",
  "216 - Hansaria Prathamik vidyalay ",
  "217 - Maharaipur S.S.K ",
  "218 - Manikadighi Primary School ",
  "219 - Chaulda Basuli Primary School ",
  "220 - Nischinta gramchandi Primary School ",
  "221 - Bilachaulda Prathamik vidyalay ",
  "222 - Hatbarhpatna S.S.K ",
  "223 - Jumki High School ",
  "224 - Jumki Primary School ",
  "225 - Shimulia Bard Prathamik vidyalay ",
  "226 - Chirulia Prathamik vidyalay ",
  "227 - Chirulia Prathamik vidyalay ",
  "228 - Chirulia Bibartan vidyapith ",
  "229 - Baligeria Madan Mohan Aadarsha vidyapith ",
  "230 - Kalshapota Primary School ",
  "231 - Bolkushda Prathamik vidyalay ",
  "232 - Bolkushda S.S.K ",
  "233 - Nehalia Primary School ",
  "234 - Chatla Primary School (Purbangsha) ",
  "235 - Chatla Haripara Primary School ",
  "236 - Chatla Haripara Primary School ",
  "237 - Bahalia Prathamik vidyalay ",
  "238 - Bahalia Prathamik vidyalay ",
  "239 - Bamunia Primary School ",
];
