export const EGRA_1_OPTIONS = [
  "1 - Teantulia Shararang N,N,High School ",
  "2 - Teantulia Shararang N,N,High School ",
  "3 - Shararang Prathamik Vidyalay ",
  "4 - Tentulia Primary School ",
  "5 - Kaurda Prathamik vidyalay ",
  "6 - Kaurda Prathamik vidyalay ",
  "7 - Barida Anganwadi Kendra (No.-7) Room - 1",
  "8 - Barida Patna Prathamik vidyalay ",
  "9 - Barida Prathamik vidyalay ",
  "10 - Barida Prathamik vidyalay ",
  "11 - Barttana Harisabha Prathamik vidyalay ",
  "12 - Bartana S.S.K ",
  "13 - Barttana Board Prathamik vidyalay ",
  "14 - Khalina Prathamik vidyalay ",
  "15 - Khalina Prathamik vidyalay ",
  "16 - Madhabpur Primary School ",
  "17 - Kalyanpur S.S.K ",
  "18 - Bayespur Prathamik vidyalay ",
  "19 - Bataspur Primary School ",
  "47 - Kainthor Ramchandrapur K.P. High School ",
  "48 - Kismat Ghatuia Mahendra Primary School ",
  "49 - Harichak Prathamik vidyalay ",
  "50 - Erendabar Primary School ",
  "51 - Errendabar SSK ",
  "52 - Mahabishra Balaram Primary School ",
  "53 - Mahabishra I.C.D.S Centre ",
  "54 - Nijdanta Prathamik vidyalay ",
  "55 - Amipara S.S.K ",
  "114 - Kashimpur Primary School ",
  "115 - Ailan Primary School ",
  "116 - Baronihari Primary School Room-1 ",
  "117 - Baranihari Upper Primary School ",
  "118 - Ramkrishnapur S.S.K ",
  "119 - Sannihari Prathamik vidyalay ",
  "120 - Chhatri Vivekananda vidyabhaban (Paschimangsha) ",
  "121 - Chhatri Vivekananda vidyabhaban (Paschimangsha) ",
  "122 - Chhatri Harijan Primary School ",
  "123 - Chhatri Harijan Primary School ",
  "124 - Chhatri Nilkantha S.S.K ",
  "125 - Chhatri 2No,Prahaladchandra Primary School(Purbangsha) ",
  "126 - Chhatri 2No,Prahaladchandra Primary School(Purbangsha) ",
  "127 - Rasan Chalkbandi Primary vidyalay ",
  "128 - Rasan Chalkbandi Primary vidyalay ",
  "129 - Rasan Jagannath Primary School ",
  "130 - Rasan Jagannath Primary School ",
  "131 - Kudi proper Primary School ",
  "132 - Kudi proper Primary School ",
  "133 - Naraharipur Prathamik Vidyalay ",
  "134 - Kamardiha Prathamik School ",
  "135 - Benachakri Primary School ",
  "136 - Telami Prathamik vidyalay ",
  "137 - Hamarjita Prathamik vidyalay ",
  "138 - Satkhanda Prathamik Vidyalay ",
  "139 - Jerthan 1 No Prathamik School ",
  "140 - Jerthan 1 No Prathamik School ",
  "141 - Jarthan Gayaprasad vidyapith ",
  "142 - Jerthan Purba S.S.K ",
  "143 - Jarthan Gayaprasad vidyapith ",
  "144 - Jerthan 2 No Prathamik vidyalay ",
  "145 - Kiya Prathamik vidyalay ",
  "146 - Kiya S.S.k ",
  "147 - Dakshin Asda Prathamik vidyalay ",
  "148 - Alangiri Prathamik vidyalay ",
  "149 - Alangiri Radhabinod vidyapith ",
  "150 - Alangiri Radhabinod vidyapith ",
  "151 - Alangiri Pitambar Nabatirtha Primary School ",
  "152 - Alangiri S.S.K ",
  "153 - Panchrol Special Primary School (Dakshinangsha) ",
  "154 - Panchrol Special Primary School (Uttarangsha) ",
  "155 - Panchrol Special Primary School (Uttarangsha) ",
  "156 - Panchrol Board Primary School ",
  "157 - Panchrol Higher Secondary School (Paschimangsha) ",
  "158 - Panchrol Higher Secondary School (Paschimangsha) ",
  "159 - Rayda Prathamik vidyalay ",
  "160 - Bilbara S.S.K ",
  "161 - Baya Prathamik vidyalay ",
  "162 - Kalyanpur Prathamik vidyalay ",
  "163 - Dhusurda Primary School ",
  "164 - Bagmari Prathamik vidyalay ",
  "165 - Bagmari Prathamik vidyalay ",
  "166 - Gahabi Prathamik vidyalay ",
  "167 - Aruya S.S.K ",
  "168 - Kashbagola 1No Prathamik vidyalay ",
  "169 - Kashbagola 1No Prathamik vidyalay ",
  "170 - Kasbagola F,O, B, Highmadrasa ",
  "171 - Kasbagola F,O, B, Highmadrasa ",
  "172 - Kashbagola 2No Primary vidyalay ",
  "173 - Kashbagola 2No Primary vidyalay ",
  "174 - Purushottampur Primary School ",
  "175 - Malida Primary School ",
  "176 - Telami Highschool ",
  "177 - GopinathpurS.S.K ",
  "178 - Khodkul Primary School ",
  "179 - Ranisai Prathamik vidyalay ",
  "180 - Sahara High School ",
  "181 - Alipur Primary School ",
  "182 - Sahara Pallishri Primary School ",
  "183 - Satkania Harijan Primary School ",
  "184 - Dakshin Shipur Primary School ",
  "185 - Shipur Keshabeswar High School ",
  "186 - Sinduria Kripasindhu Primary School ",
  "187 - Dolbard Shunia Prathamik Vidyalay ",
  "188 - Harihar Shunia Primary School ",
  "189 - Tahalia Ramkrishna Smriti Prathamik vidyalay ",
  "190 - Pandua S.S.k ",
  "191 - Chorpalia Shri shri Basanti Vidyapith ",
  "192 - Chorpalia Primary School ",
  "193 - Negua Sundar Narayan High School ",
  "194 - Ramchandrapur Prathamik vidyalay ",
  "195 - Shikrachakdai Prathamik Vidyalay ",
  "196 - Amdai Pachim Pry. School ",
  "197 - Aamdai Kaderia Primary School ",
  "198 - Aamdai Kaderia Primary School ",
  "199 - Khalshutia Prathamik vidyalay ",
  "200 - Khalshutia Prathamik vidyalay ",
  "201 - Purunda Sarbamangala Primary School (Uttarangsha) ",
  "202 - Purunda Sarbamangala Primary School (Uttarangsha) ",
  "203 - Mirjapur Primary School ",
  "204 - Barada Magunicharan Junior Basic School ",
  "205 - Barada Magunicharan Junior Basic School ",
  "206 - Barada Magunicharan junior high school ",
  "207 - Solpatia Prathamik vidyalay ",
  "208 - Amadpur Primary School ",
  "209 - Akandi Junior Basic School ",
  "210 - Bhatshalia Prathamik vidyalay ",
  "211 - Negua R B C Pathshala ",
  "212 - Nutiberh Primary School ",
  "213 - Radhapur Prathamik vidyalay ",
  "214 - Jagulia Primary School ",
  "215 - Arjuni Prathamik vidyalay ",
  "216 - Hansaria Prathamik vidyalay ",
  "217 - Maharaipur S.S.K ",
  "218 - Manikadighi Primary School ",
  "219 - Chaulda Basuli Primary School ",
  "220 - Nischinta gramchandi Primary School ",
  "221 - Bilachaulda Prathamik vidyalay ",
  "222 - Hatbarhpatna S.S.K ",
  "223 - Jumki High School ",
  "224 - Jumki Primary School ",
  "225 - Shimulia Bard Prathamik vidyalay ",
  "226 - Chirulia Prathamik vidyalay ",
  "227 - Chirulia Prathamik vidyalay ",
  "228 - Chirulia Bibartan vidyapith ",
  "229 - Baligeria Madan Mohan Aadarsha vidyapith ",
  "230 - Kalshapota Primary School ",
  "231 - Bolkushda Prathamik vidyalay ",
  "232 - Bolkushda S.S.K ",
  "233 - Nehalia Primary School ",
  "234 - Chatla Primary School (Purbangsha) ",
  "235 - Chatla Haripara Primary School ",
  "236 - Chatla Haripara Primary School ",
  "237 - Bahalia Prathamik vidyalay ",
  "238 - Bahalia Prathamik vidyalay ",
  "239 - Bamunia Primary School ",
];

export const EGRA_2_OPTIONS = [
  "56 - Krishnapur S.S,K ",
  "57 - Rukminipur Kanai Lal vidyapith ",
  "58 - Rukminipur Primary School ",
  "59 - Saharda Prathamik vidyalay ",
  "60 - Sultanpur S.S.K ",
  "61 - Uttar Erenda Prathamik vidyalay ",
  "62 - Erenda Highschool ",
  "63 - Erenda Highschool ",
  "64 - Shushunia Primary School ",
  "65 - Erenda Prathamik vidyalay ",
  "66 - Uttar Panthai Prathamik vidyalay ",
  "67 - Rajendrachak Prathamik vidyalay ",
  "68 - Rajendrachak Prathamik vidyalay ",
  "69 - Urijalkar S.S.K Room - 1",
  "70 - Onsarisha S.S.K. ",
  "71 - Keutgeria vidyasagar Highschool ",
  "72 - Ultabad S.S.K. ",
  "73 - Hurkuchia Prathamik vidyalay ",
  "74 - Shilampur 1 No Primary School ",
  "75 - Shilampur No.2 Primary School ",
  "76 - Ultabad Shilampur Nilakantha Primary School ",
  "77 - Shyampur Ashram Uchcha Prathamik vidyalay ",
  "78 - Bidurpur Prathamik vidyalay ",
  "78A - Bidurpur Prathamik vidyalay ",
  "79 - Sahapur Prathamik vidyalay ",
  "80 - Urdhabpur jhatucharan Prathamik vidyalay ",
  "81 - Daudpur Binapani Uchcha Prathamik vidyalay ",
  "82 - Daudpur Binapani Uchcha Prathamik vidyalay ",
  "83 - Uttar Daudpur Prathamik vidyalay ",
  "84 - Daudpur Samabay Krishi Unnayan Samity ",
  "85 - Tajpur Sammilita Atyayik Prathamik vidyalay ",
  "86 - Tajpur Nimna Buniyadi Prathamik vidyalay ",
  "87 - Tajpur vidyasagar Primary School ",
  "88 - Nimakbar Sitalasebak shantamoni Prathamik vidyalay (Uttarangsha)",
  "89 - Nimakbar Sitalasebak shantamoni Prathamik vidyalay ",
  "90 - Kamalpur Primary vidyalay ",
  "91 - Kamalpur Primary vidyalay ",
  "92 - Bhatda Gandhi Maydan S.S.K ",
  "93 - Bhatda Board Prathamik vidyalay ",
  "94 - Bhatda Gadadhar Primary School ",
  "95 - Baincha Prathamik vidyalay ",
  "96 - Baincha Nazrul S.S.K ",
  "97 - Farakpara S.S.K ",
  "98 - Balighai Fakirdas Highschool ",
  "99 - Tolakana Primary School ",
  "100 - Mallikpur Primary School ",
  "101 - Uttar Baranidhi S.S.K ",
  "102 - Dakshin baranidhi basanta s.s.k ",
  "103 - Tentuliagiri Prathamik Vidyalaya ",
  "104 - Tentuliagiri S.S.K. ",
  "105 - Nayapara Primary School ",
  "106 - Balighai Sikshasadan ",
  "107 - Dakshinchak Srikrishna Board Prathamik vidyalay ",
  "108 - Dakshinchak Highschool ",
  "109 - Khejurda Tentuliagiri Nazrul Madhyamik Siksha Kendra ",
  "110 - Khejurda Prathamik Vidyalay ",
  "111 - Daudpur Prathamik vidyalay ",
  "112 - Alipur Sukanta S.S.K ",
  "113 - Ariapota Prathamik vidyalay ",
  "240 - Khurutia Nimnabuniadi vidyalay ",
  "241 - Khurutia Nimnabuniadi vidyalay ",
  "242 - Teghari Primary School ",
  "243 - Lalpur Prathamik vidyalay ",
  "244 - Paniparul Mukteswar Uchhavidyalay ",
  "245 - Paniparul Mukteswar Uchhavidyalay ",
  "246 - Baincha Primary School ",
  "247 - Pashcim Paniparul Prathamik vidyalay ",
  "248 - Debidaspur Gandhi Harijan Primary School ",
  "249 - Debidaspur Gandhi Harijan Primary School ",
  "250 - Kapasda Shitala Primary School ",
  "251 - Kapasda Shitala Primary School ",
  "252 - Chirkunpada Primary School ",
  "253 - Chandalda Narayani Primary School ",
  "254 - Sarisha Primary School ",
  "255 - Aranga Mahendra Prathamik vidyalay ",
  "256 - Aranga Vivekananda S.S.K ",
  "257 - Paniparul Primary School ",
  "258 - Lalpur Mukteswar Girls Haighschool ",
  "259 - Kultikri Prahallad vidyapith (Singha Para) ",
  "260 - Kultikri Harekrishna prathamik vidyalay ",
  "261 - Kultikri Harekrishna prathamik vidyalay ",
  "262 - Khagada Pallishri Highschool ",
  "263 - Khagda Prathamik vidyalay ",
  "264 - Chhotokhagda Primary School ",
  "265 - Dubda Deshapran Birendra vidyapith ",
  "266 - Dubda Deshapran Birendra vidyapith ",
  "267 - Dubda Deshapran Prathamik Bidyalay ",
  "268 - Dubda 2No Uttam Charan Prathamik vidyalay ",
  "269 - Dubda Saradamoni Harizon Prathamik Vidyalay ",
  "270 - Dubda 1No Prathamik vidyalay ",
  "271 - Dubda Bani vidyapith ",
  "272 - Asti Primary School ",
  "273 - Geria Prathamik vidyalay ",
  "274 - Gholdubda Prathamik vidyalay ",
  "275 - Ghol Dubda S.S.K ",
  "276 - Shnakapada Prathamik vidyalay ",
  "277 - Shnakapada Prathamik vidyalay ",
  "278 - Rasulpur Dakshinbar Prathamik vidyalay ",
  "279 - Sanbheri Kalu Roy Primary School ",
  "280 - Chhoto Rasulpur Prathamik vidyalay (Jelepara) ",
  "281 - Baranalgeria jogendra Primary vidyalay(Maiti Para) ",
  "282 - Baranalgeria New Primary School ",
  "283 - Atbati Annapurna Bidyamandir ",
  "284 - Chhotonalgeria Primary vidyalay(Uttarangsha)Haripara ",
  "285 - Naskarpur Bhubaneswari Prathamik vidyalay ",
  "286 - Ganeswarpur Prathamik vidyalay (Giri Para) ",
  "287 - Ganeswarpur Bhagbat Prathamik vidyalay (Payrapara) ",
  "288 - Egra Patna Prathamik vidyalay (Karapara) ",
  "289 - Mahespur Ramakanta Prathamik vidyalay (Maitipara) ",
  "290 - Beta Hat Primary School ",
  "291 - Shyamharibar Samabay Adarsha vidyalay ",
  "292 - ShyamhariBar Primary School ",
  "293 - Shyamharibar Tripalli Primary School ",
  "294 - Basudebpur Sabuj Sanggha (Pathagar) ",
  "295 - Uttar Basudebpur Primary School ",
  "296 - Basudebpur Haripriya Institiution ",
  "297 - Basudevpur Primary School ",
  "298 - Jinandapur Primary School ",
  "299 - Bhabanichak Highschool (Uchcha Madhyamik) ",
  "300 - Bhabanichak Raghunath Primary School ",
  "301 - Basudebpur Kiranmaye Primary School ",
  "302 - Naskarpur Basudebpur Matilal Prathamik vidyalay ",
  "303 - Chirulia Srinathchandra vidyapith ",
  "304 - Dulalpur Prathamik vidyalay ",
  "305 - Dulalpur Benepukur S.S.K ",
  "306 - Bachchhipur Primary School ",
  "307 - Motaghat S.S.K(Patra Para) ",
];

export const EGRA_MUNICIPALITY_OPTIONS = [
  "20 - Dalaluya Prathamik vidyalay Room- 1 ",
  "21 - Comunity Centre (Ulipur, Ward No. 2) Room - 1",
  "22 - Dalaluya Prathamik vidyalay Room-2 ",
  "23 - Aluya Prathamik vidyalay ",
  "24 - Bangshidharpur S.S.K ",
  "25 - Kasba Egra Prathamik Vidyalaya Room - 1",
  "26 - Egra Swarnamayee Girls High School ",
  "27 - Egra J L High School Room-2 ",
  "28 - Egra J L High School Room-2 ",
  "29 - Egra J L High School Room-3 ",
  "30 - Purushottampur Prathamik vidyalay ",
  "31 - Purushottampur Prathamik vidyalay ",
  "32 - Purusottampur S.S.K ",
  "33 - Purusottampur Community Hall ",
  "34 - Aklabad Prathamik vidyalay ",
  "35 - Egara S,S,B.College ",
  "36 - Egara S,S,B.College ",
  "37 - Jagannathapur Pallimangal Prathamik vidyalay ",
  "38 - Jagannathapur Pallimangal Prathamik vidyalay ",
  "39 - Adalabad Bhagabati Special Pra: School ",
  "40 - Adalabad Bhagabati Special Pra: School ",
  "41 - Comunity Centre (Kasba Egra, Ward No. 13) Room - 1",
  "42 - Kasba Egra Community Hall (Ward No. 12) Room - 2",
  "43 - Kashba Junior Basic School (Purbangsha) ",
  "44 - Kashba Junior Basic School (Purbangsha) ",
  "45 - Kashba Shitala Prathamik vidyalay ",
  "46 - Kashba Shitala Prathamik vidyalay ",
];

export const EGRA_MAPS_MAPPING = {
  1: "https://maps.app.goo.gl/VLnnbBCHCtXgRwTu8",
  2: "https://maps.app.goo.gl/VLnnbBCHCtXgRwTu8",
  3: "https://maps.app.goo.gl/dJFkSMXKv2T5SHQy5",
  4: "https://maps.app.goo.gl/VcrR3rh7bnmydcZg6",
  5: "https://maps.app.goo.gl/qCDQz53N3dhtas966",
  6: "https://maps.app.goo.gl/2m77B4jAv2CRcaUF6",
  7: "https://maps.app.goo.gl/zR8fuTMXC45p51ZM9",
  8: "https://maps.app.goo.gl/2tbF2eM8BtqKFvcQ9 ",
  9: "https://maps.app.goo.gl/gTxhoqHimZ6MkDPk7 ",
  10: "https://maps.app.goo.gl/TnQL9mVcf6ScPNRp6 ",
  11: "https://maps.app.goo.gl/TXPtjLbrY2AcUc2s5 ",
  12: "https://maps.app.goo.gl/eVyn8TwKBKAz5CCy8 ",
  13: "https://maps.app.goo.gl/HJU8obqJEKLbnuo77 ",
  14: "https://maps.app.goo.gl/apteBanKVVR2G1Ks9 ",
  15: "https://maps.app.goo.gl/GGWkfB2sG32NnTkH8 ",
  16: "https://maps.app.goo.gl/xC883FnLodB37tgV9 ",
  17: "https://maps.app.goo.gl/LneEtCEHyFbG4noc9 ",
  18: "https://maps.app.goo.gl/QneB8vBqyzeL1Cd5A ",
  19: "https://maps.app.goo.gl/DMzAV9RUZ3hBndYQ6 ",
  20: "https://maps.app.goo.gl/vaEcQEFS6EtJArPv5 ",
  21: "https://maps.app.goo.gl/GY2XHw6hvGbjdM9o9",
  22: "https://maps.app.goo.gl/KDftpTb9HSmaCibs5 ",
  23: "https://maps.app.goo.gl/Pz5gLMcmT8hYKBWw5 ",
  24: "https://maps.app.goo.gl/37iZBRwwReQ8YRXg7 ",
  25: "https://maps.app.goo.gl/LR3MSaoCjwvuidQb6 ",
  26: "https://maps.app.goo.gl/2Wuu3qykxjF8XPF26 ",
  27: "https://maps.app.goo.gl/rZGJMCGUyxsVPE6S7 ",
  28: "https://maps.app.goo.gl/zz3cbyNUhK8k7nAb6 ",
  29: "https://maps.app.goo.gl/zz3cbyNUhK8k7nAb6 ",
  30: "https://maps.app.goo.gl/88V3zdg4p9zKJW5t5 ",
  31: "https://maps.app.goo.gl/88V3zdg4p9zKJW5t5 ",
  32: "https://maps.app.goo.gl/m3pPn7bN6FfDxqg26 ",
  33: "https://maps.app.goo.gl/ePEjama6PtGez5Uu9 ",
  34: "https://maps.app.goo.gl/qm8Deiq1wuVAPYodA  ",
  35: "https://maps.app.goo.gl/cBGRkWARHB5t1QWx7 ",
  36: "https://maps.app.goo.gl/cBGRkWARHB5t1QWx7 ",
  37: "https://maps.app.goo.gl/RZuX4FPbimE68N6j9 ",
  38: "https://maps.app.goo.gl/RZuX4FPbimE68N6j9 ",
  39: "https://maps.app.goo.gl/VrUxVxNbDkxP17VC9 ",
  40: "https://maps.app.goo.gl/VrUxVxNbDkxP17VC9 ",
  41: "https://maps.app.goo.gl/gVJSj918mADc6kzu7 ",
  42: "https://maps.app.goo.gl/gVJSj918mADc6kzu7 ",
  43: "https://maps.app.goo.gl/tNokyecH37oAXwGs6 ",
  44: "https://maps.app.goo.gl/XBK8SLiV81xuBRS7A ",
  45: "https://maps.app.goo.gl/jqGYkczT7Y9uLcXa9 ",
  46: "https://maps.app.goo.gl/jqGYkczT7Y9uLcXa9 ",
  47: "https://maps.app.goo.gl/X8fanZ7u2qqzy2o38 ",
  48: "https://maps.app.goo.gl/H1DZSm4UGqcEZYU6A ",
  49: "https://maps.app.goo.gl/DgDi9kAp8BShDKA96  ",
  50: "https://maps.app.goo.gl/d3r2D5RHwbHyNceT9 ",
  51: "https://maps.app.goo.gl/d3r2D5RHwbHyNceT9 ",
  52: "https://maps.app.goo.gl/Gqjy61ffVBDu6JyZA ",
  53: "https://maps.app.goo.gl/Y1FZD9Gis7u5J88d9 ",
  54: "https://maps.app.goo.gl/nBrJHiAxHy2fWLzc7 ",
  55: "https://maps.app.goo.gl/Wfb8xgeAHaiNoxt89  ",
  56: "https://maps.app.goo.gl/H6Undvpc3CsM5rRK9 ",
  57: "https://maps.app.goo.gl/dHwCkHpeZzin8B728 ",
  58: "https://maps.app.goo.gl/bEFWepFTXhpKkhho7 ",
  59: "https://maps.app.goo.gl/9sPNm1Q9YptbvZb98 ",
  60: "https://maps.app.goo.gl/YLe6ajDcXzga7kcw6 ",
  61: "https://maps.app.goo.gl/5J6KwPKfuuWehtDx6 ",
  62: "https://maps.app.goo.gl/2k4iJythYNYW4YnC6 ",
  63: "https://maps.app.goo.gl/Ufhu7pto7Xra14Jj9 ",
  64: "https://maps.app.goo.gl/CwZHeeQvbA6QijJZ8 ",
  65: "https://maps.app.goo.gl/rWU7uaLhPmWmidh59 ",
  66: "https://maps.app.goo.gl/PJuNp2ctJTmHpQvE7 ",
  67: "https://maps.app.goo.gl/AvJ72yPcFChuZLGb6 ",
  68: "https://maps.app.goo.gl/Z3p81vUF9aWwhjuV8 ",
  69: "https://maps.app.goo.gl/7iYacHPbmiGfnnuz7 ",
  70: "https://maps.app.goo.gl/AKv8ZgiUsGevdaVY7 ",
  71: "https://maps.app.goo.gl/z5btLbBSbgvrFHBJ8 ",
  72: "https://maps.app.goo.gl/35YxNCukr5AS7AUk9 ",
  73: "https://maps.app.goo.gl/X1huKbAV8qLchRWG6 ",
  74: "https://maps.app.goo.gl/5xswoKZHKx6yPUYe6 ",
  75: "https://maps.app.goo.gl/2SQXAx4FcrzC6yfm7 ",
  76: "https://maps.app.goo.gl/bxut3LfsDAGm6vTv5 ",
  77: "https://maps.app.goo.gl/bTAyXYwuWhmQdZ7e6 ",
  78: "https://maps.app.goo.gl/nwRNYu6JGaZoYzhT8 ",
  79: "https://maps.app.goo.gl/tbEziGo18Mj8PmGCA ",
  80: "https://maps.app.goo.gl/GVgbVaX147XBnvaC9 ",
  81: "https://maps.app.goo.gl/M49UbhGjPevF5yjg9",
  82: "https://maps.app.goo.gl/M49UbhGjPevF5yjg9 ",
  83: "https://maps.app.goo.gl/NPqFJfXQ69xA9esS7 ",
  84: "https://maps.app.goo.gl/NHt3d2mNV8LN2tdZ9 ",
  85: "https://maps.app.goo.gl/v2KpVwLM3N7beMH6A ",
  86: "https://maps.app.goo.gl/Vk5kFeabTzzCLwAB7 ",
  87: "https://maps.app.goo.gl/gArn3BshoQ6NkDg67 ",
  88: "https://maps.app.goo.gl/jQAeyo8m6WunNNPR9 ",
  89: "https://maps.app.goo.gl/Ex2CAcXWWbL92hni9 ",
  90: "https://maps.app.goo.gl/KtJoMDKvxzyUSdDT7 ",
  91: "https://maps.app.goo.gl/QM1siQXFGFn1VFsW7 ",
  92: "https://maps.app.goo.gl/Yet7x94FHDu8vYQV6 ",
  93: "https://maps.app.goo.gl/gBv9tcRyuZ1yTVgX6 ",
  94: "https://maps.app.goo.gl/vw2bGBT68aN6nNSX9 ",
  95: "https://maps.app.goo.gl/8JcswQJ5sB3s8S6F6 ",
  96: "https://maps.app.goo.gl/MMxdmMzE2P1pPJB99 ",
  97: "https://maps.app.goo.gl/z5HU3fX71roYmVmDA ",
  98: "https://maps.app.goo.gl/KUtyGeiB9SEVpyrY8 ",
  99: "https://maps.app.goo.gl/kFN7Hk3kaTUbfmPp9",
  100: "https://maps.app.goo.gl/6EdpNUwk6YS3r9fF7",
  101: "https://maps.app.goo.gl/pYFeeDwsqLyGKZ1k7",
  102: "https://maps.app.goo.gl/9bv2BBGrrXMJJNeS8",
  103: "https://maps.app.goo.gl/LJZGdL47NXNk6qYaA",
  104: "https://maps.app.goo.gl/q1n4VZpNrq7KonEw6",
  105: "https://maps.app.goo.gl/Lcf6Upw1fPFjEYru6",
  106: "https://maps.app.goo.gl/u1vgCkgF5742Adnd7",
  107: "https://maps.app.goo.gl/Vj3qDsz4SEvy2bxU6",
  108: "https://maps.app.goo.gl/bbMPF13EKAX4i8uWA",
  109: "https://maps.app.goo.gl/5t35MuTeyqqkYehp7",
  110: "https://maps.app.goo.gl/P4TgkKF5aW7wQJrm7",
  111: "https://maps.app.goo.gl/y2k5BVdoebQBttTw5",
  112: "https://maps.app.goo.gl/ezG8dHCHQBBCy44p6",
  113: "https://maps.app.goo.gl/jd2LEdvTDrwpJBDh7",
  114: "https://maps.app.goo.gl/NEcX18L16YyNz3vy5",
  115: "https://maps.app.goo.gl/1fBUhprhQKm8p1FZ8",
  116: "https://maps.app.goo.gl/9sP9mSJQTUKZqbsN7",
  117: "https://maps.app.goo.gl/8ymXndHNEbFBKSzp9",
  118: "https://maps.app.goo.gl/NZYFy6WEvZKnW9vW8",
  119: "https://maps.app.goo.gl/mPXHYTXrLnXdxTZq8",
  120: "https://maps.app.goo.gl/Mu9wuKFTsiEHS99S7",
  121: "https://maps.app.goo.gl/8Py7MTSigZ6HCzFW9",
  122: "https://maps.app.goo.gl/p9huuReYmH2W28EH7",
  123: "https://maps.app.goo.gl/6fFzYBYczJfgCbB47",
  124: "https://maps.app.goo.gl/2C5SVBjvM7Gp8QEw6",
  125: "https://maps.app.goo.gl/v8XAdGUYH35LD35t8",
  126: "https://maps.app.goo.gl/YbHc8qRQ6qhKiYscA",
  127: "https://maps.app.goo.gl/hd53auV3ugsBGHRx6",
  128: "https://maps.app.goo.gl/1NX8AQkcertZDuV88",
  129: "https://maps.app.goo.gl/PreRA1wcta4Yf8sn9",
  130: "https://maps.app.goo.gl/DqukPL19RxC95e2d9",
  131: "https://maps.app.goo.gl/Nhp3YUXqo6b9Gx6K9",
  132: "https://maps.app.goo.gl/8m7iorsWLJv25pp69",
  133: "https://maps.app.goo.gl/r1hUDgvTzfgvJQZp6",
  134: "https://maps.app.goo.gl/dhMBVLzhTCZZ2xz57",
  135: "https://maps.app.goo.gl/Ryj5fq2Uag4KLUw57",
  136: "https://maps.app.goo.gl/2oLCSFe2624qaopj8",
  137: "https://maps.app.goo.gl/u8nYVkN4ABMiJDVT7",
  138: "https://maps.app.goo.gl/cMp43TLUZRQkvRTX8",
  139: "https://maps.app.goo.gl/sDcjoerJYCGJaei98 ",
  140: "https://maps.app.goo.gl/nvkaLCmy3uHq8sH89",
  141: "https://maps.app.goo.gl/WG7mA1aHumdAQSKM7",
  142: "https://maps.app.goo.gl/rSE7CdthV8wewtv7A",
  143: "https://maps.app.goo.gl/H9MjiJbo56JKxh79A",
  144: "https://maps.app.goo.gl/MWnajtM7rRRynDoV6",
  145: "https://maps.app.goo.gl/LTGS5khnFF6AsGfQA",
  146: "https://maps.app.goo.gl/qPvafxpv4s4tPQxP6",
  147: "https://maps.app.goo.gl/Jr5S1o1QgLQLGvYHA",
  148: "https://maps.app.goo.gl/Ei5ELVdWZZ6sq2wr8",
  149: "https://maps.app.goo.gl/SKW3WjnjsYgR26jF8",
  150: "https://maps.app.goo.gl/A3oGGGEtdrwNHXQB6",
  151: "https://maps.app.goo.gl/bnhFz6NC24SuGyb18",
  152: "https://maps.app.goo.gl/SqgoPNT6a9SgRjvs9",
  153: "https://maps.app.goo.gl/c5sGfHeXD5Y3WMxf6",
  154: "https://maps.app.goo.gl/cwcwboLdYRm2vCkL9",
  155: "https://maps.app.goo.gl/57BDH4NHxPu76F2f8",
  156: "https://maps.app.goo.gl/VW3xYhkpt7ztUvQ59",
  157: "https://maps.app.goo.gl/RJ9yuZpydwk7RbnQ9",
  158: "https://maps.app.goo.gl/NW3vaE74kyhrBsnJ7",
  159: "https://maps.app.goo.gl/7UNGuyq6iiFoL2k98",
  160: "https://maps.app.goo.gl/989xR99JqwxXSo7u8",
  161: "https://maps.app.goo.gl/X7iSCeYZVnpoz8a89",
  162: "https://maps.app.goo.gl/pMwVLcw5sM5mgW9r5",
  163: "https://maps.app.goo.gl/m8LKZ4SikGBKWV8g6",
  164: "https://maps.app.goo.gl/EDBysdhLxJnx53abA",
  165: "https://maps.app.goo.gl/CsAaS7EVd84Cb8zHA",
  166: "https://maps.app.goo.gl/SA9BMacuPffvZbbU6",
  167: "https://maps.app.goo.gl/SnqUR4tGG5tBWpUKA",
  168: "https://maps.app.goo.gl/hqX282EiHpybBEyG7",
  169: "https://maps.app.goo.gl/pMMPpiAkhiFUHdxt9",
  170: "https://maps.app.goo.gl/ymettAHX45uKLqXM9",
  171: "https://maps.app.goo.gl/ZCcLXCdcpxmJp8xJ8",
  172: "https://maps.app.goo.gl/ijuQsQgd1TtcXSvU7",
  173: "https://maps.app.goo.gl/KfkoHmLwRg54vXLH8",
  174: "https://maps.app.goo.gl/WDStPcqCeF91eKVP8",
  175: "https://maps.app.goo.gl/QUJsLvVNgZXEWjdy5",
  176: "https://maps.app.goo.gl/HZePGPLAfoso4DDq6",
  177: "https://maps.app.goo.gl/j6jpg7dgX9t9zYTJ8",
  178: "https://maps.app.goo.gl/uN3D8H9fzgLAibZR8",
  179: "https://maps.app.goo.gl/WYvAmXZRkHEYBjPaA",
  180: "https://maps.app.goo.gl/1k9Qz1jK9aRWhqK7A",
  181: "https://maps.app.goo.gl/NqdRmKTR2yebkVEa6",
  182: "https://maps.app.goo.gl/MQ4YRs1Zhz16pQVh8",
  183: "https://maps.app.goo.gl/c5GZDz3cHxQeCxzE9",
  184: "https://maps.app.goo.gl/JuADzCL36dpiUo5r5",
  185: "https://maps.app.goo.gl/L8i4uKDjB858kk717",
  186: "https://maps.app.goo.gl/QM6662bYrdZxWqGV8",
  187: "https://maps.app.goo.gl/xyg95H3t6kCqeTPw5",
  188: "https://maps.app.goo.gl/NMSBTma5eeYDy9NG8",
  189: "https://maps.app.goo.gl/MF2JJR5rFBH5GUog6",
  190: "https://maps.app.goo.gl/Hi7h7ptWVzitswKF7",
  191: "https://maps.app.goo.gl/V8wbUGvrERajXQtM9",
  192: "https://maps.app.goo.gl/PV9UCMZsW5cKnGyj8",
  193: "https://maps.app.goo.gl/uEBKzaha5tvVn3naA",
  194: "https://maps.app.goo.gl/1LRex9k2fcTvTSJc7",
  195: "https://maps.app.goo.gl/tSPqXGtGPmzph9fi9",
  196: "https://maps.app.goo.gl/MFrMcUxapbNuyf1p7",
  197: "https://maps.app.goo.gl/niXNj12PCMJt2KG5A",
  198: "https://maps.app.goo.gl/fJVQWRF6XiZTR3Hx9",
  199: "https://maps.app.goo.gl/Q3aTc8EXc9zAnkd28",
  200: "https://maps.app.goo.gl/QQzYiez4PHoareez8",
  201: "https://maps.app.goo.gl/iJi5h2feWySkWrx6A",
  202: "https://maps.app.goo.gl/BuoVeko82YQJoba38",
  203: "https://maps.app.goo.gl/wjG7B9NVL3uzxUU4A",
  204: "https://maps.app.goo.gl/tnUPCzF86fK8qhk76",
  205: "https://maps.app.goo.gl/kodDb6cPqsjWEZiy5",
  206: "https://maps.app.goo.gl/RcVTXxSMhgMjufbS6",
  207: "https://maps.app.goo.gl/ooMxT9qnnD6bnEDr6",
  208: "https://maps.app.goo.gl/WgMcEd1SCj1bDo4e7",
  209: "https://maps.app.goo.gl/V3H7LmdjPTYDihco7",
  210: "https://maps.app.goo.gl/EPr6aF9eixVKdpku9",
  211: "https://maps.app.goo.gl/QFascWnXwcvqwHXc9",
  212: "https://maps.app.goo.gl/m6rmXxQ4xiwHxTPUA",
  213: "https://maps.app.goo.gl/PafqV7AcseJvU59M8",
  214: "https://maps.app.goo.gl/g9qUH8fwWYYtXZfDA",
  215: "https://maps.app.goo.gl/QLMc7YVLGtovNPTF8",
  216: "https://maps.app.goo.gl/ZJzRQYdMWT2Hc42Z7",
  217: "https://maps.app.goo.gl/ogvbMwsSein98kaV9",
  218: "https://maps.app.goo.gl/FXpSKxo76BFBK7Gg7",
  219: "https://maps.app.goo.gl/CeiBBYqKzdx3xGwU7",
  220: "https://maps.app.goo.gl/qCby6AC8G7sivZyf7",
  221: "https://maps.app.goo.gl/hBkU2D3y962PiUyBA",
  222: "https://maps.app.goo.gl/fY4iyMAYGBARkbMK9",
  223: "https://maps.app.goo.gl/bHijwvj2HTMB3L188",
  224: "https://maps.app.goo.gl/eH2QfTMwkJ5u1Bbn9",
  225: "https://maps.app.goo.gl/oiX6bTPJvVKtdmkw9",
  226: "https://maps.app.goo.gl/hCa9wq3tg6GUxCy57",
  227: "https://maps.app.goo.gl/hCa9wq3tg6GUxCy57",
  228: "https://maps.app.goo.gl/hCa9wq3tg6GUxCy57",
  229: "https://maps.app.goo.gl/SgryVMvZaMmrDJzCA",
  230: "https://maps.app.goo.gl/bscNobxQQK4jFGKB7",
  231: "https://maps.app.goo.gl/vG7baFR5mhHuRgow6",
  232: "https://maps.app.goo.gl/m5cc35iNAeJTLfir5",
  233: "https://maps.app.goo.gl/ozAxJM6Yzt4j3osU8",
  234: "https://maps.app.goo.gl/3nVjgJdd48zuUSqZ8",
  235: "https://maps.app.goo.gl/qH4sFgtAr8M2D3zX9",
  236: "https://maps.app.goo.gl/gae3ci768Zu1vqTo6",
  237: "https://maps.app.goo.gl/RWWW9MTtfxgeUdx8A",
  238: "https://maps.app.goo.gl/RWWW9MTtfxgeUdx8A",
  239: "https://maps.app.goo.gl/TNZRxaEQTquRx9F1A",
  240: "https://maps.app.goo.gl/sbX9aDqTohzrKvC28",
  241: "https://maps.app.goo.gl/5pHkFbis3kM4KeAi8",
  242: "https://maps.app.goo.gl/wrnz1PuRYcNkBYxEA",
  243: "https://maps.app.goo.gl/4ry1uHTSsY3mHGcA6",
  244: "https://maps.app.goo.gl/sachAP4TwGhp5MfE8",
  245: "https://maps.app.goo.gl/27Vyr46jhje6GnX38",
  246: "https://maps.app.goo.gl/yaCQC9Gb6cMx5MQo9",
  247: "https://maps.app.goo.gl/dDJVNULNN7vBCtSB6",
  248: "https://maps.app.goo.gl/X1qmQNs9dSCTMcC86",
  249: "https://maps.app.goo.gl/xzYf5ept6T7ezywSA",
  250: "https://maps.app.goo.gl/5CGMo7vMVufdhMgm7",
  251: "https://maps.app.goo.gl/BdGmp88sAxnoafjK9",
  252: "https://maps.app.goo.gl/cP28kYMnnRHiTjgYA",
  253: "https://maps.app.goo.gl/x1HK8hErhY8895V47",
  254: "https://maps.app.goo.gl/SZe6SShdWzWijzhdA",
  255: "https://maps.app.goo.gl/uJkrCsvn7ji7su7X8",
  256: "https://maps.app.goo.gl/Gh29cE4Pc6aXqW1P8",
  257: "https://maps.app.goo.gl/VmDQPxYUHypDgvzw5",
  258: "https://maps.app.goo.gl/y4wwL9hEygKsAjad6",
  259: "https://maps.app.goo.gl/B35px65LL2FTGkzk7",
  260: "https://maps.app.goo.gl/jvnt5136hfTuWeRW6",
  261: "https://maps.app.goo.gl/PXzr5SQrsqXZ85gD9",
  262: "https://maps.app.goo.gl/8vYjSDmUAM9whXKy9",
  263: "https://maps.app.goo.gl/ZfqDmmM2KV5pEmrK9",
  264: "https://maps.app.goo.gl/diC4TSJBRQBY3Kfq9",
  265: "https://maps.app.goo.gl/TmHMr3gQNXqCuPTz6",
  266: "https://maps.app.goo.gl/GDmozC8o45as9tE76",
  267: "https://maps.app.goo.gl/jKQHF4AHmm6zrwo97",
  268: "https://maps.app.goo.gl/8zfuwyRr5hymk4Hh9",
  269: "https://maps.app.goo.gl/QquL1UDsoj1obVUY7",
  270: "https://maps.app.goo.gl/ya6rkY52ocWM1U4m6",
  271: "https://maps.app.goo.gl/u6S6fV8etaCJWyUf8",
  272: "https://maps.app.goo.gl/6bo2j8J7y3uxv1AXA",
  273: "https://maps.app.goo.gl/GWREDtcjZTssV82V9",
  274: "https://maps.app.goo.gl/7VQS7UhMmLNnRuoT8",
  275: "https://maps.app.goo.gl/uM2dSscuFnstPD92A",
  276: "https://maps.app.goo.gl/57f29zWqt1ycz8aE9",
  277: "https://maps.app.goo.gl/XpsBMEDKHNeipeKq7",
  278: "https://maps.app.goo.gl/7ZhzMqYDgUHhxCfg7",
  279: "https://maps.app.goo.gl/1JqGAMQ6iVCw2Dsk9",
  280: "https://maps.app.goo.gl/gmZgyNUTX5scgxTh7",
  281: "https://maps.app.goo.gl/BmoTgoKSMr24LuXz7",
  282: "https://maps.app.goo.gl/dioUvEM3tJjFgXBX9",
  283: "https://maps.app.goo.gl/coUC7GKBQFjDCXs28",
  284: "https://maps.app.goo.gl/h5PJHcqtse9uNbMm7",
  285: "https://maps.app.goo.gl/uikeTszxxK87cwQm8",
  286: "https://maps.app.goo.gl/U7GxjPJKAWsu95UX7",
  287: "https://maps.app.goo.gl/63FbwLLLNhUJJdKf7",
  288: "https://maps.app.goo.gl/Ch7YDKpCS2rGg6HV8",
  289: "https://maps.app.goo.gl/Fpeq6Ep6BrPyq8XUA",
  290: "https://maps.app.goo.gl/KwrrwhwBeneryhgM9",
  291: "https://maps.app.goo.gl/q9oZbwRR11n7XuJ37",
  292: "https://maps.app.goo.gl/5AQoGc8eRpc2mZFu6",
  293: "https://maps.app.goo.gl/w56xxLMoFvTD28DB9",
  294: "https://maps.app.goo.gl/4kGaw382kiRRAkFq6",
  295: "https://maps.app.goo.gl/XrLo4pV9QAi43AvJ9",
  296: "https://maps.app.goo.gl/MkWgT5Rebpc4dsWc7",
  297: "https://maps.app.goo.gl/uPZFoesEC1J1Qu4z8",
  298: "https://maps.app.goo.gl/jcR9Gxe2f16vzi426",
  299: "https://maps.app.goo.gl/su4SjSDyRn89HYRo9",
  300: "https://maps.app.goo.gl/RMw8EiCQ4Xs1o9np9",
  301: "https://maps.app.goo.gl/uM5yLJLiea1Gv4B66",
  302: "https://maps.app.goo.gl/hNQjWdELgirm2pjr7",
  303: "https://maps.app.goo.gl/PSf4s3zgtVZeWZY58",
  304: "https://maps.app.goo.gl/xDSBairwkfNMhhLd7",
  305: "https://maps.app.goo.gl/JxcJ7hmGKsXARcx26",
  306: "https://maps.app.goo.gl/4Pp5eg2fUkCQmbC87",
  307: "https://maps.app.goo.gl/r7wtwnpbwkqtZW8P8",
};
