export const PATASHPUR_1_OPTIONS = [
  "1 - Naipur Santisudha Institution Room No. - 1",
  "2 - Naipur Santisudha Institution Room No. - 2",
  "3 - Madhupur Madhusudan Upper Primary School",
  "4 - Madhabpur Primary School",
  "5 - Sanya Primary School",
  "6 - Mirzapur Primary School",
  "7 - Chakgopal Primary School",
  "8 - Alamchak Primary School",
  "9 - Padima Primary School",
  "10 - Padima SSK",
  "11 - Belda Upper Primary School",
  "12 - Belda SSK",
  "13 - Maninathpur Primary School",
  "14 - Nankar Kadamgeria Primary School",
  "15 - Chandpur Harocharan Vidyamandir (High)",
  "16 - Ambi SSK",
  "17 - Bhadua Primary School",
  "18 - Argara Primary School",
  "19 -  Ayodhyapur Primary School",
  "20 - Kanakpur Sarbamangala Primary School",
  "21 - Kanaidangar Primary School",
  "22 - Tulsichara Primary School",
  "23 - Gokulpur Debnathpalli SSK",
  "24 - Gokulpur Primary School (W) Room No. - 1",
  "25 - Gokulpur Primary School (E) Room No. - 2",
  "26 - Barbaria Primary School",
  "27 - Mahespur Primary School",
  "28 - Amarpur Hiralal Vidyaniketan",
  "29 - Amarpur Hat Primary School",
  "30 - Hajipur Primary School",
  "31 - Amarpur Prathamik Vidyalaya",
  "32 - Amarpur Kharialpara Primary School",
  "33 - Pusha Primary School",
  "34 - Gokulpur Madanmohan Sikshaniketan (High)",
  "35 - Tapinda Primary School",
  "36 - Kharigerya Primary School",
  "37 - Biswanathpur Girls High School",
  "38 - Teparpara Prathamik Vidyalaya",
  "39 - Teparpara Sashibhusan Vidyamandir",
  "40 - Chharadighi Primary School",
  "41 - Sasthapally Sambhunath High School",
  "42 - Satbahini Primary School",
  "43 - Paschimjali Ramchak Primary School",
  "44 - Khidirpur Primary School",
  "45 - Kharan Primary School",
  "46 - Kharan SSK",
  "47 - Kunjaberia Primary School",
  "48 - Selmabad Sarojini Vidyaniketan",
  "49 - Purba Selmabad Primary School",
  "50 - Trisulabandh Primary School",
  "51 - Uttar Selmabad Free Primary School",
  "52 - Gopalpur Union Rakhal Vidyalaya",
  "53 - Gopalpur Satyamoyee Balika Vidyalaya",
  "54 - Soulaveri Primary School Room No. - 1",
  "55 - Soulaveri Primary School Room No. - 2",
  "136 - Kalmaghat Primary School",
  "137 - Narpada Primary School",
  "138 - Hatibandh MSK",
  "139 - Amarshi Raghunath High School Room No. - 1",
  "140 - Amarshi Raghunath High School Room No. - 2",
  "141 - Amarshi Brindabanchandra Balika Vidyalaya (High)",
  "142 - Amarshi Raghunath High School Room No. - 3",
  "143 - Amarshi Primary School (N) Room No. - 1",
  "144 - Amarshi Primary School (S) Room No. - 2",
  "145 - Purba Amarshi Primary School",
  "146 - Purba Amarshi Sashibushan Primary School",
  "147 - Shyamkhola Primary School",
  "148 - Shyamkhola NCLP School",
  "149 - Agarpara SSK",
  "150 - Balabhadrapur Vivekananda Vidyapity Room No. - 1",
  "151 - Soulaveri ICDS Centre",
  "152 - Balabhadrapur Vivekananda Vidyapity Room No. - 2",
  "153 - Taladiha 1 No. Board Primary School Room No. - 1",
  "154 - Taladiha 1 No. Board Primary School Room No. - 2",
  "155 - Taladiha 2 No. Primary School",
  "156 - Taladiha Gourchak Primary School",
  "157 - Saridaspur Primary School Room No. - 1",
  "158 - Saridaspur Primary School Room No. - 2",
  "159 - Gopalsingpur Primary School",
  "160 - Barsankar Primary School (East) Room No. - 1",
  "161 - Barsankar Primary School (West) Room No. - 2",
  "162 - Sanmajigaon Primary School",
  "163 - Mahammadpur Primary School",
  "164 - Panchuria Sudhanyamoyee Grils School",
  "165 - Manglamaro Pallybharati Balika Vidyalaya",
  "166 - Dhakrabanka Deshapran Siksha Niketan (Jr. High)",
  "167 - Bhagabanpur Primary School",
  "168 - Amgechia Primary School",
  "169 - Ramkhali SSK",
  "170 - Chistipurveri Adarsha Primary School",
  "171 - Gonaraveri SSK",
  "172 - Palparaveri Primary School",
  "173 - Gadaiveri Primary School",
  "174 - Baruipur Primary School Room No. - 1",
  "175 - Baruipur Primary School Room No. - 2",
  "176 - Rambasan Primary School",
  "177 - Yogoda Satsangha Palpara High School Room No. - 1",
  "178 - Yogoda Satsangha Palpara High School Room No. - 2",
  "179 - Tota Falkara Primrary School",
  "180 - Yogoda Satsangha Palpara Primary School",
  "181 - Yogoda Satsangha Palpara Balika Vidyalaya (High)",
  "182 - Dhankar Primary School Room No. - 1",
  "183 - Dhankar Primary School Room No. - 2",
  "184 - Talchitkini Pirmary School Room - 1",
  "185 - Talchitkini Pirmary School Room - 2",
  "186 - Barmukhal Primary School",
  "187 - Sahapur Swapneswar Primary School Room No. - 1",
  "188 - Sahapur Swapneswar Primary School Room No. - 2",
  "189 - Golara Adarsha Primary School Room No. - 1",
  "190 - Golara Adarsha Primary School Room No. - 2",
  "191 - Rupadighi ICDS",
  "192 - Chistipur Primary School (West)",
  "193 - Chistipur Primary School (East)",
  "194 - Nankar Primary School",
  "195 - Baruibar Primary School",
  "196 - Barhat Jr. Basic High School",
  "197 - Maishali Primary School",
  "198 - Nakibasan Primary School",
  "199 - Ektarpur Primary School",
  "200 - Barhat Sambhunath Banipith (High)",
  "201 - Pratappur SSK",
  "202 - Payranagari Primary School",
  "203 - Kulrakhi Primary School",
  "204 - Katranka Primary School",
  "205 - Sadatpur Primary School",
  "206 - Dulalpur SSK",
  "207 - Barabhagia Jr.  Basic School",
  "208 - Saiyadpur Primary School",
  "209 - Sankargeria SSK",
  "210 - Ashariabandh Primary School",
  "211 - Kutubpur Primary School",
  "212 - Hirasagar Primary School Room No. - 1",
  "213 - Hirasagar Primary School Room No. - 2",
  "214 - Kantapukhuria SSK",
  "215 - Paharpur Primary School",
  "216 - Singda Primary School",
  "217 - Makrampur Nilkantha Sikshasadan Room No. - 1",
  "218 - Sahapur Primary School",
  "219 - Makrampur Nilkantha Sikshasadan Room No. - 2",
  "220 - Khakuriadanga Primary School",
  "221 - Goalda Primary School",
  "222 - Goalda SSK",
  "223 - Banamalichak Primary School",
  "224 - Tarat Primary School Room No. - 1",
  "225 - Tarat Primary School Room No. - 2",
  "226 - Irda Prathamik School",
  "227 - Ramchandra Primary School",
];

export const PATASHPUR_1_MAP_OPTIONS = [
  "https://maps.app.goo.gl/JFz5gSNya9t2MtSA7",
  "https://maps.app.goo.gl/uME1JzfV87CzRYjU8",
  "https://maps.app.goo.gl/sf8wjrVH7GL8kAY98 ",
  "https://maps.app.goo.gl/Y9NL8niR9NhuBRtUA",
  "https://maps.app.goo.gl/t1hkgWoybtKSSu4b6",
  "https://maps.app.goo.gl/MXZd3c1GTtkwe1vM6",
  "https://maps.app.goo.gl/XXRB8Bv5J6tSMJB2A",
  "https://maps.app.goo.gl/DkL9Wc8VsnZG1YdD8",
  "https://maps.app.goo.gl/vaQKK3LRJykWjFiG9",
  "https://maps.app.goo.gl/zbmj6i5bPz9t3YPU7",
  "https://maps.app.goo.gl/gKsXGXwYv2ct66CJA",
  "https://maps.app.goo.gl/XoGw2enQJPA1coE67",
  "https://maps.app.goo.gl/YWbiDopdnBr1LfRN7",
  "https://maps.app.goo.gl/9PQZcPEzSdP5aPmv9",
  "https://maps.app.goo.gl/QntKeT6nehyvXSKc8",
  "https://maps.app.goo.gl/kcJiPpa8WMRepWcK7",
  "https://maps.app.goo.gl/Hoqy91gjranV8gde9",
  "https://maps.app.goo.gl/6rMaKRjGMcKDTLNB9",
  "https://maps.app.goo.gl/fQ19WxbLwuaQkEep7",
  "https://maps.app.goo.gl/4FHoz2aYhJv28j4m6",
  "https://maps.app.goo.gl/McuJrYD8iEqMD8CBA",
  "https://maps.app.goo.gl/tS8qiPvPA4MZXzzn7",
  "https://maps.app.goo.gl/688SCbx31LPcsb3e8",
  "https://maps.app.goo.gl/1FYJuiCMvccy6h3Y9",
  "https://maps.app.goo.gl/1FYJuiCMvccy6h3Y9",
  "https://maps.app.goo.gl/1XvUrbBHpUv1sa237",
  "https://maps.app.goo.gl/CCLtsfcjzeeSqWEL7",
  "https://maps.app.goo.gl/b6dy73hPSVP6xLVBA",
  "https://maps.app.goo.gl/R16ifjjULiUbbqFk6",
  "https://maps.app.goo.gl/vgoh8yqpJ7ReYiir6",
  "https://maps.app.goo.gl/YpaVbuehW8o9f6hE6",
  "https://maps.app.goo.gl/k71F1iH8ActFu83f9",
  "https://maps.app.goo.gl/XhRNDQo2Y56AAarb9",
  "https://maps.app.goo.gl/xjoGrEBgJrsEsW7HA",
  "https://maps.app.goo.gl/zBHfzxv4hLueRjXc9",
  "https://maps.app.goo.gl/CmMk4fQuNbvE57VY6",
  "https://maps.app.goo.gl/PwezsQ6aHqVdPRig9",
  "https://maps.app.goo.gl/EbLxd4QsnzQQCyo89",
  "https://maps.app.goo.gl/J8KjtubVEHXyVFaJ7",
  "https://maps.app.goo.gl/znMDNFu2QLMEQke69",
  "https://maps.app.goo.gl/RtzgH6XU59kCo3UQ7",
  "https://maps.app.goo.gl/38StJG32TjMSQjyh6",
  "https://maps.app.goo.gl/Xm58hhpbFepoU9LT8",
  "https://maps.app.goo.gl/yBCAkvYqEYvPKCcr7",
  "https://maps.app.goo.gl/gBFxKicGzUFADCC96",
  "https://maps.app.goo.gl/YCQswnxM48rKkrRi9",
  "https://maps.app.goo.gl/hkV8ncsxPgoSyWGN8",
  "https://maps.app.goo.gl/44ZUbzo6gf5ssK3B6",
  "https://maps.app.goo.gl/ZxMn8P6xz5jbngKH7",
  "https://maps.app.goo.gl/ErZTM3uN5h3n8uow9",
  "https://maps.app.goo.gl/cmf7TJXDB4P39mQv9",
  "https://maps.app.goo.gl/tb2oNeLzP7TzrnxF8",
  "https://maps.app.goo.gl/W13Ed4EEKbH9CZ8y6",
  "https://maps.app.goo.gl/qTdPK4p5KfSbNAer8",
  "https://maps.app.goo.gl/qTdPK4p5KfSbNAer8",
  "https://maps.app.goo.gl/39QQQVNL2NJweaTm9",
  "https://maps.app.goo.gl/e8kT2wgzPb4kqGmu8",
  "https://maps.app.goo.gl/w57DgpFyyixyTokn7",
  "https://maps.app.goo.gl/g8eR49hTGv4KdEyZ6",
  "https://maps.app.goo.gl/wtrchunDwFfqRrTH9",
  "https://maps.app.goo.gl/6DjeQ8LXPuVHYzn19",
  "https://maps.app.goo.gl/g8eR49hTGv4KdEyZ6",
  "https://maps.app.goo.gl/RKwtr1WTmuh2nCz9A",
  "https://maps.app.goo.gl/RKwtr1WTmuh2nCz9A",
  "https://maps.app.goo.gl/JfAuFzdKFhZzTWVm8",
  "https://maps.app.goo.gl/VKm5JKjJh1Xy9sMw9",
  "https://maps.app.goo.gl/DuAqird1abSFBQmD7",
  "https://maps.app.goo.gl/HNSWR1CsHazcpyjz6",
  "https://maps.app.goo.gl/rUKXx9TbW2MTqCMs7",
  "https://maps.app.goo.gl/KNcgqFw7arRbBDRCA",
  "https://maps.app.goo.gl/r45pCLPoH2sCLAjY6",
  "https://maps.app.goo.gl/EqfgfqGmQ6JVxa4y7",
  "https://maps.app.goo.gl/b1q3yAEFDSkPSHf38",
  "https://maps.app.goo.gl/6CL3xUMrQkao93Xn8",
  "https://maps.app.goo.gl/EW9FB3DKQLXguPFe7",
  "https://maps.app.goo.gl/kUJ4ihwnhKJoaB6Y9",
  "https://maps.app.goo.gl/tWU97gUqbk7rJ7vZ9",
  "https://maps.app.goo.gl/TbatM3wygriqzSbP6",
  "https://maps.app.goo.gl/gEHz2BKnY3fDGZ2d8",
  "https://maps.app.goo.gl/LabJawrduLy1hKaZ6",
  "https://maps.app.goo.gl/LabJawrduLy1hKaZ6",
  "https://maps.app.goo.gl/m9HtvB2kky8Qc6RR8",
  "https://maps.app.goo.gl/46dqwqLTVeXKC36H7",
  "https://maps.app.goo.gl/onW1Grm6SwscQ6hi8",
  "https://maps.app.goo.gl/9zqrHNs3BWwLrw8c9",
  "https://maps.app.goo.gl/9GwRYSPibUFYqoUf9",
  "https://maps.app.goo.gl/mJ6y3Lxj78REeT2D6",
  "https://maps.app.goo.gl/YpLsnUVXsgt9xQW48",
  "https://maps.app.goo.gl/Rrwb7VzwFQVVCnnn7",
  "https://maps.app.goo.gl/B2jgjqx57on5Huxe8",
  "https://maps.app.goo.gl/7JfkTV5puALZSh9m7",
  "https://maps.app.goo.gl/sjXbZZ1jBAQwVam77",
  "https://maps.app.goo.gl/rgoCPFzNE3b3dAzd8",
  "https://maps.app.goo.gl/Qm9vG1sPf9Bu7EVG7",
  "https://maps.app.goo.gl/Qm9vG1sPf9Bu7EVG7",
  "https://maps.app.goo.gl/BRWXu24NA6M62sjDA",
  "https://maps.app.goo.gl/XU1ZtgDZ3W5B6v51A",
  "https://maps.app.goo.gl/XU1ZtgDZ3W5B6v51A",
  "https://maps.app.goo.gl/Q8hhkU9k9sjjjFCc8",
  "https://maps.app.goo.gl/gH3aAQnHQbu6aL1y5",
  "https://maps.app.goo.gl/Sk9uXTpSWVodUF4SA",
  "https://maps.app.goo.gl/eH97G4GpnMpCun5F6",
  "https://maps.app.goo.gl/eH97G4GpnMpCun5F6",
  "https://maps.app.goo.gl/Z681M9ueuuAPkXoW7",
  "https://maps.app.goo.gl/2vqZhuahi9JEhvzR9",
  "https://maps.app.goo.gl/mNazPUukTTzpsHjr5",
  "https://maps.app.goo.gl/dr8uH8p7pG5vtSGC8",
  "https://maps.app.goo.gl/dr8uH8p7pG5vtSGC8",
  "https://maps.app.goo.gl/7Mt3qDj3PY94oWQM6",
  "https://maps.app.goo.gl/SE541X3HwqUr5vNd8",
  "https://maps.app.goo.gl/f9rL6UxYPGGfgnB39",
  "https://maps.app.goo.gl/n16yVQwFQqVBiuT96",
  "https://maps.app.goo.gl/n16yVQwFQqVBiuT96",
  "https://maps.app.goo.gl/QNs8TDHGC19bceZP6",
  "https://maps.app.goo.gl/94JfEaiymtEKGrH18",
  "https://maps.app.goo.gl/iEpr2kEvUXkUHRBc8",
  "https://maps.app.goo.gl/9XvH7rAQha8h2Mn26",
  "https://maps.app.goo.gl/HVxYbYwGZNichGp67",
  "https://maps.app.goo.gl/YMrxCRpPdtgfAvDGA",
  "https://maps.app.goo.gl/XbPW3LvrFuXEt49i6",
  "https://maps.app.goo.gl/ghwZ88p2t9BB9Gks6",
  "https://maps.app.goo.gl/71xgqYrfE4r1tsxB8",
  "https://maps.app.goo.gl/aFRSQwNbTkkqmcyB9",
  "https://maps.app.goo.gl/cJQmrG23z8KGm3iHA",
  "https://maps.app.goo.gl/PLMsm1hJWDbtKzke8",
  "https://maps.app.goo.gl/yExRSVxyVKvRjtQdA",
  "https://maps.app.goo.gl/Ga6rEPLsJjqUTuAM9",
  "https://maps.app.goo.gl/Rm31mbVihHAVqxPP7",
  "https://maps.app.goo.gl/YB5zeXG6qhSYK2Qj9",
  "https://maps.app.goo.gl/pjfCa4HjfcCRF1yX8",
  "https://maps.app.goo.gl/juMu1qRpG7w5n53i7",
  "https://maps.app.goo.gl/CHC51mtHRcCociaPA",
  "https://maps.app.goo.gl/CHC51mtHRcCociaPA",
  "https://maps.app.goo.gl/c2DvKHUD9vDkkNv37",
  "https://maps.app.goo.gl/A13DgvuFE9WpSGMaA",
  "https://maps.app.goo.gl/UrgyMEgPHSfPdkzn8",
  "https://maps.app.goo.gl/u69wry3qnSQDE68r5",
  "https://maps.app.goo.gl/VaNWey5zrR4sfU1RA",
  "https://maps.app.goo.gl/zYvd9s6EZQ2PKxxJA",
  "https://maps.app.goo.gl/6NYQgxEF4EW998q29",
  "https://maps.app.goo.gl/QETvgZBFSZChd4UD7",
  "https://maps.app.goo.gl/KNamhNrcNXDoK1927",
  "https://maps.app.goo.gl/CdYnyBnGtaPGd8bh6",
  "https://maps.app.goo.gl/ZMVZ3RnHsV8H6YuY7",
  "https://maps.app.goo.gl/vmupTwAHL4Csdvs86",
  "https://maps.app.goo.gl/eX6NoCXZx9n4vPTw5",
  "https://maps.app.goo.gl/KEvt9wn3f1DS66Rp7",
];

export const PATASHPUR_2_OPTIONS = [
  "56 - Kanpur Prathamik vidyalay ",
  "57 - Kanpur Shriguru Siksha Niketan ",
  "58 - Dainda Prathamik vidyalay ",
  "59 - Jhuria Jr. High School ",
  "60 - Kekai Prathamik vidyalay ",
  "61 - Bamunda Prathamik vidyalay (Dakshin)",
  "62 - Bamunda Junior High School ",
  "63 - Krishnapur Special Prathamik vidyalay ",
  "64 - Itachana Prathamik vidyalay ",
  "65 - Matirampur S.S.K. ",
  "66 - Haridangar High School ",
  "67 - Patashpur (Tupchibarh) Prathamik vidyalay (Purba)",
  "68 - Patashpur (Tupchibarh) Prathamik vidyalay (Paschim)",
  "69 - Chaksrikrishna Prathamik vidyalay ",
  "70 - Madhya Kashba S.S.K ",
  "71 - Selampur Prathamik vidyalay (Paschim)",
  "72 - Selampur Junior High School ",
  "73 - Patashpur Harocharan Vidyapith ",
  "74 - Kasba Patashpur Prathamik Vidyalay ",
  "75 - Satshanda Prathamik vidyalay ",
  "76 - Srikhoda Prathamik vidyalay ",
  "77 - Raghunathpur Muradpur Prathamik vidyalay ",
  "78 - Manpur Prathamik vidyalay ",
  "79 - Girisha Prathamik Vidyalay ",
  "80 - Gangasagar Primary School ",
  "81 - Mustafapur Yashoda Satsanga vidyapith (North)",
  "82 - Mustafapur Yashoda Satsanga vidyapith ",
  "83 - Barh Mustafapur Saifur S.S.K ",
  "84 - Nonakourda Prathamik vidyalay (Purba)",
  "85 - Nonakourda Sukanta S.S.K. ",
  "86 - Paschimsai Prathamik vidyalay ",
  "87 - Khar Paschimpara Prathamik vidyalay ",
  "88 - Baharda Prathamik vidyalay ",
  "89 - Khar Highschool (Uchchamadhyamik ) ",
  "90 - Ratanpur Primary School ",
  "91 - Dakshin khar S.S.K. ",
  "92 - Purba Khar S.S.K ",
  "93 - Barbatia Highschool ",
  "94 - Buran Prathamik vidyalay ",
  "95 - Kalyanpur Prathamik vidyalay (Dakshin)",
  "96 - Kalyanpur Prathamik vidyalay (Uttar)",
  "97 - Kainara Prathamik vidyalay ",
  "98 - Kainara Jr. High School ",
  "99 - Nimja Prathamik vidyalay ",
  "100 - Purushottampur Highschool ",
  "101 - Purusottompur Primary School ",
  "102 - Kashipur Prathamik vidyalay ",
  "103 - Pindarui Prathamik vidyalay ",
  "104 - Panchetgarh Prathamik vidyalay (Uttar)",
  "105 - Panchetgarh Prathamik vidyalay (Purba)",
  "106 - Panchetgarh Highschool (Paschim)",
  "107 - Panchetgarh Highschool (Dakshin)",
  "108 - Chandanpur Chaksuja Prathamik vidyalay (Uttar)",
  "109 - Chandanpur Chaksuja Prathamik vidyalay (Paschim)",
  "110 - Kharui Garh High School (Uttar)",
  "111 - Kharui Garh High School (Dakshin)",
  "112 - Lachhubarh Prathamik vidyalay ",
  "113 - Gobardhanpur S.S.K ",
  "114 - Khatuabarh Prathamik vidyalay ",
  "115 - Rautara Prathamik vidyalay ",
  "116 - Kharui Kailaschandra Uchcha Prathamik vidyalay ",
  "117 - Kharui M.I. Senior Madrasha ",
  "118 - Gobardhanpur Prathamik vidyalay ",
  "119 - Barakonyarda Board Prathamik vidyalay (Dakshin)",
  "120 - Barakonarda Junior High School ",
  "121 - Bagmari Highschool ",
  "122 - Bagmari Primary School ",
  "123 - Tikrapara Ambikamoyee Highschool ",
  "124 - Pariharpur Prathamik vidyalay ",
  "125 - Jagti Deulbarh Harijan Primary School ",
  "126 - Jagati Uchha Prathamik vidyalay ",
  "127 - Krishnanagar Prathamik vidyalay ",
  "128 - Mangalpur Prathamik vidyalay Room 1",
  "129 - Mangalpur Junior High School ",
  "130 - Majna Radhakrishna Prathamik vidyalay Room - 1",
  "131 - Majna Radhakrishna Prathamik vidyalay Room - 2",
  "132 - Srirampur Haraprasad Highschool ",
  "133 - Kishornagar Patna Prathamik vidyalay ",
  "134 - Dhusurda Board Prathamik vidyalay ",
  "135 - Dhusurda Board Prathamik vidyalay (South)",
  "228 - Bhairabdanri Junior High School ",
  "229 - Bhairabadanri Prathamik vidyalaya (Dakshin)",
  "230 - Southkhanda Prathamik vidyalay ",
  "231 - Southkhanda West Primary School ",
  "232 - Chakbhabani Harijan Prathamik Vidyalay ",
  "233 - Chakbhabani Madan Kishor Nirodamayee vidyayatan ",
  "234 - Bamanbarh Jr. High School ",
  "235 - Ghonga Sashanka S.S.K ",
  "236 - Uttar Choumukh Harijan Prathamik vidyalay ",
  "237 - Sukhakhola Prathamik vidyalay ",
  "238 - Gopalpur Primary school ",
  "239 - Mallikpur Harijan Prathamik vidyalay ",
  "240 - Mallikpur Bajanbarh S.S.K ",
  "241 - Bara Udaypur Anath Board Prathamik vidyalay ",
  "242 - Patna Prathamik Vidyalay ",
  "243 - Chhotoudaypur Gopinath Prathamik vidyalay (Uttar)",
  "244 - Chhotoudaypur Gopinath Prathamik vidyalay (Dakshin)",
  "245 - Brajakishorpur Deshapran Gangaram High School ",
  "246 - Brajakishorepur Primary School ",
  "247 - Agraniya Prathamik Vidyalay ",
  "248 - Batia Byomkeswar Prathamik vidyalay ",
  "249 - Bhattabarh Primary School ",
];

export const PATASHPUR_2_MAP_OPTIONS = [
  "https://maps.app.goo.gl/mYEKpmLghn1GKnCYA",
  "https://maps.app.goo.gl/76d6z21A9VLXfvik9",
  "https://maps.app.goo.gl/NKE18vNnuHi7r9dSA",
  "https://maps.app.goo.gl/5uQyZobVEJB6Et878",
  "https://maps.app.goo.gl/UG7BDi3nnwcpLqDMA",
  "https://maps.app.goo.gl/LY8XnzGS7sZMKD9n9",
  "https://maps.app.goo.gl/qckPc2k7yogY26L7A",
  "https://maps.app.goo.gl/QL5zKPvuAXkdZoit6",
  "https://maps.app.goo.gl/5hRd4Np7FoCp5Lr5A",
  "https://maps.app.goo.gl/gaaNYZoqKnyXmJ4q6",
  "https://maps.app.goo.gl/Vo4UjoarNzPSmaPV7",
  "https://maps.app.goo.gl/ZWxgegBPtpmttDdS6",
  "https://maps.app.goo.gl/ZWxgegBPtpmttDdS6",
  "https://maps.app.goo.gl/qUUSupBeNbv3PsJz7",
  "https://maps.app.goo.gl/nRejZud6de92bD6N6",
  "https://maps.app.goo.gl/iQg9cXaWpjjwT7b6A",
  "https://maps.app.goo.gl/iQg9cXaWpjjwT7b6A",
  "https://maps.app.goo.gl/BWBxUyE6LAad1E718",
  "https://maps.app.goo.gl/YP2i4isNbrnwTG4v5",
  "https://maps.app.goo.gl/jS4MDxXWbTWCgwrL9",
  "https://maps.app.goo.gl/CmMmVqPXjXwRrcX56",
  "https://maps.app.goo.gl/VR5s5rzkgSy5LJW76",
  "https://maps.app.goo.gl/XWYgkX7nZfysC6kz8",
  "https://maps.app.goo.gl/SUyDZCe2buPHVMUC7",
  "https://maps.app.goo.gl/cZK2UhSeRvsvRzZR8",
  "https://maps.app.goo.gl/fseP1Xjaj1RtqCUi9",
  "https://maps.app.goo.gl/xYmZVZ4YLEUsij196",
  "https://maps.app.goo.gl/gz4nmMVQFACwUT619",
  "https://maps.app.goo.gl/5egr5P4XRCP3hEc6A",
  "https://maps.app.goo.gl/LeNyUr6LswxyUvRX7",
  "https://maps.app.goo.gl/dGW8xQtYmwjKAJJU7",
  "https://maps.app.goo.gl/GeoWDrtBk2JU7YbF7",
  "https://maps.app.goo.gl/D1aCqrkoK89XeCRa8",
  "https://maps.app.goo.gl/vbpcUY1xTzdYfQNMA",
  "https://maps.app.goo.gl/q6yENHSTR5qHYmGC7",
  "https://maps.app.goo.gl/yrYjkqfU9TGUfEQi8",
  "https://maps.app.goo.gl/AUPP9zGqvXipwvPY6",
  "https://maps.app.goo.gl/gAjG6zVppvPYfCHD9",
  "https://maps.app.goo.gl/G1VHdTKf43Bt8YU87",
  "https://maps.app.goo.gl/S2Yi9j63UD3Ei4jk6",
  "https://maps.app.goo.gl/21TeVkjwmXN4cF3y5",
  "https://maps.app.goo.gl/Vvq96LbbV35fjmRQA",
  "https://maps.app.goo.gl/3cdRgdJUSsKEnYjj8",
  "https://maps.app.goo.gl/yxYRPJR6h8j7TDmv5",
  "https://maps.app.goo.gl/Dtyjxmao6McWSB947",
  "https://maps.app.goo.gl/ov5iuCrNSjFKfsJb7",
  "https://maps.app.goo.gl/ApeqqbNJP5Fsh7P7A",
  "https://maps.app.goo.gl/MuCbmUZHH67tBBYT6",
  "https://maps.app.goo.gl/Qbq5HzzBTFWh1H9E8",
  "https://maps.app.goo.gl/TQeMSMHhhd3f6iU26",
  "https://maps.app.goo.gl/VjUfpz9MyqLD6JLq6",
  "https://maps.app.goo.gl/hKEH5S6tYgB5MiBZ6",
  "https://maps.app.goo.gl/eYsAtgRrf6R6vSwJ9",
  "https://maps.app.goo.gl/9UVFTU4ATU6Ec2h16",
  "https://maps.app.goo.gl/btXXCTWJogLdjsPN9",
  "https://maps.app.goo.gl/L3x8KcHAu9pK4FAt8",
  "https://maps.app.goo.gl/zHkXomnBP5NmLSiP7",
  "https://maps.app.goo.gl/h1MVPfNtZ4rLX2Jf8",
  "https://maps.app.goo.gl/rbEhpNSFb1DZbpwK7",
  "https://maps.app.goo.gl/Vbsi9qkkvhMK9gAE9",
  "https://maps.app.goo.gl/1zPYgbS5mQha6rZN9",
  "https://maps.app.goo.gl/SNynhWiv3ScsMh38A",
  "https://maps.app.goo.gl/Ecxhmf6RGk5xdpBPA",
  "https://maps.app.goo.gl/Y3wk4m114SfpFfTg6",
  "https://maps.app.goo.gl/LaaNGbkYDKv1i9Jg8",
  "https://maps.app.goo.gl/dRJZukivTGyGFhYw8",
  "https://maps.app.goo.gl/zpdDkxhuyFSAHCvh9",
  "https://maps.app.goo.gl/8Nmk6KRjQFTTMeJC8",
  "https://maps.app.goo.gl/52hYwxrMpRDoV2ySA",
  "https://maps.app.goo.gl/ti9KkicaMK6NBgNw8",
  "https://maps.app.goo.gl/johhBTK9wPNx4B2V9",
  "https://maps.app.goo.gl/d633bF2VKsbFSYSNA",
  "https://maps.app.goo.gl/1H41jiP1iK4GwDiN7",
  "https://maps.app.goo.gl/VjByuqu71cP7K5zr6",
  "https://maps.app.goo.gl/EU4Au839ZY1aN9qK9",
  "https://maps.app.goo.gl/96hpgp3nWr2gMdMBA",
  "https://maps.app.goo.gl/g7ogi1cvbMiEuoVd8",
  "https://maps.app.goo.gl/sxhtE3ZD74DG428o9",
  "https://maps.app.goo.gl/VR2AG1cm2oc7mkhTA",
  "https://maps.app.goo.gl/MREivUnjqQ4asyZN9",
  "https://maps.app.goo.gl/YztyKZvSSDejatKYA",
  "https://maps.app.goo.gl/7h8XEZ5U795ciiwc8",
  "https://maps.app.goo.gl/2onCznv5uEexub2r5",
  "https://maps.app.goo.gl/ptMBVfKfBea9ikTj7",
  "https://maps.app.goo.gl/aFsLuSqfTSi8CaBk6",
  "https://maps.app.goo.gl/u1Wt8XhB9gfbTGLPA",
  "https://maps.app.goo.gl/tD1fZu9QCQLSJdmM8",
  "https://maps.app.goo.gl/xJFqkFvjYxdanZPJ8",
  "https://maps.app.goo.gl/nhcwbHuUEAV21unV9",
  "https://maps.app.goo.gl/Qa2mqBT7XUqEcPwR9",
  "https://maps.app.goo.gl/hpwYLRBXbnHXFvYVA",
  "https://maps.app.goo.gl/DTUzTLSJQs4vX9aN9",
  "https://maps.app.goo.gl/PaECRpYdAMH7WKYo7",
  "https://maps.app.goo.gl/D67o7qmDNxJ2Gd3R9",
  "https://maps.app.goo.gl/K7R4zrkgVuyZeX15A",
  "https://maps.app.goo.gl/x83PgrhrRo3PzB7y6",
  "https://maps.app.goo.gl/JZtW2MwA1p8jFRBW9",
  "https://maps.app.goo.gl/ajHuGyV78zaVWuPP6",
  "https://maps.app.goo.gl/bJ2Nw1gMwbMek4ss6",
  "https://maps.app.goo.gl/3xXVxPSbV8piLwJi7",
  "https://maps.app.goo.gl/Wyde8GwsDWzJVTeeA",
  "https://maps.app.goo.gl/LBq2FDXyKWQj12M3A",
];
