export const PATASHPUR_1_OPTIONS = [
  "1 - Naipur Santisudha Institution Room No. - 1",
  "2 - Naipur Santisudha Institution Room No. - 2",
  "3 - Madhupur Madhusudan Upper Primary School",
  "4 - Madhabpur Primary School",
  "5 - Sanya Primary School",
  "6 - Mirzapur Primary School",
  "7 - Chakgopal Primary School",
  "8 - Alamchak Primary School",
  "9 - Padima Primary School",
  "10 - Padima SSK",
  "11 - Belda Upper Primary School",
  "12 - Belda SSK",
  "13 - Maninathpur Primary School",
  "14 - Nankar Kadamgeria Primary School",
  "15 - Chandpur Harocharan Vidyamandir (High)",
  "16 - Ambi SSK",
  "17 - Bhadua Primary School",
  "18 - Argara Primary School",
  "19 -  Ayodhyapur Primary School",
  "20 - Kanakpur Sarbamangala Primary School",
  "21 - Kanaidangar Primary School",
  "22 - Tulsichara Primary School",
  "23 - Gokulpur Debnathpalli SSK",
  "24 - Gokulpur Primary School (W) Room No. - 1",
  "25 - Gokulpur Primary School (E) Room No. - 2",
  "26 - Barbaria Primary School",
  "27 - Mahespur Primary School",
  "28 - Amarpur Hiralal Vidyaniketan",
  "29 - Amarpur Hat Primary School",
  "30 - Hajipur Primary School",
  "31 - Amarpur Prathamik Vidyalaya",
  "32 - Amarpur Kharialpara Primary School",
  "33 - Pusha Primary School",
  "34 - Gokulpur Madanmohan Sikshaniketan (High)",
  "35 - Tapinda Primary School",
  "36 - Kharigerya Primary School",
  "37 - Biswanathpur Girls High School",
  "38 - Teparpara Prathamik Vidyalaya",
  "39 - Teparpara Sashibhusan Vidyamandir",
  "40 - Chharadighi Primary School",
  "41 - Sasthapally Sambhunath High School",
  "42 - Satbahini Primary School",
  "43 - Paschimjali Ramchak Primary School",
  "44 - Khidirpur Primary School",
  "45 - Kharan Primary School",
  "46 - Kharan SSK",
  "47 - Kunjaberia Primary School",
  "48 - Selmabad Sarojini Vidyaniketan",
  "49 - Purba Selmabad Primary School",
  "50 - Trisulabandh Primary School",
  "51 - Uttar Selmabad Free Primary School",
  "52 - Gopalpur Union Rakhal Vidyalaya",
  "53 - Gopalpur Satyamoyee Balika Vidyalaya",
  "54 - Soulaveri Primary School Room No. - 1",
  "55 - Soulaveri Primary School Room No. - 2",
  "136 - Kalmaghat Primary School",
  "137 - Narpada Primary School",
  "138 - Hatibandh MSK",
  "139 - Amarshi Raghunath High School Room No. - 1",
  "140 - Amarshi Raghunath High School Room No. - 2",
  "141 - Amarshi Brindabanchandra Balika Vidyalaya (High)",
  "142 - Amarshi Raghunath High School Room No. - 3",
  "143 - Amarshi Primary School (N) Room No. - 1",
  "144 - Amarshi Primary School (S) Room No. - 2",
  "145 - Purba Amarshi Primary School",
  "146 - Purba Amarshi Sashibushan Primary School",
  "147 - Shyamkhola Primary School",
  "148 - Shyamkhola NCLP School",
  "149 - Agarpara SSK",
  "150 - Balabhadrapur Vivekananda Vidyapity Room No. - 1",
  "151 - Soulaveri ICDS Centre",
  "152 - Balabhadrapur Vivekananda Vidyapity Room No. - 2",
  "153 - Taladiha 1 No. Board Primary School Room No. - 1",
  "154 - Taladiha 1 No. Board Primary School Room No. - 2",
  "155 - Taladiha 2 No. Primary School",
  "156 - Taladiha Gourchak Primary School",
  "157 - Saridaspur Primary School Room No. - 1",
  "158 - Saridaspur Primary School Room No. - 2",
  "159 - Gopalsingpur Primary School",
  "160 - Barsankar Primary School (East) Room No. - 1",
  "161 - Barsankar Primary School (West) Room No. - 2",
  "162 - Sanmajigaon Primary School",
  "163 - Mahammadpur Primary School",
  "164 - Panchuria Sudhanyamoyee Grils School",
  "165 - Manglamaro Pallybharati Balika Vidyalaya",
  "166 - Dhakrabanka Deshapran Siksha Niketan (Jr. High)",
  "167 - Bhagabanpur Primary School",
  "168 - Amgechia Primary School",
  "169 - Ramkhali SSK",
  "170 - Chistipurveri Adarsha Primary School",
  "171 - Gonaraveri SSK",
  "172 - Palparaveri Primary School",
  "173 - Gadaiveri Primary School",
  "174 - Baruipur Primary School Room No. - 1",
  "175 - Baruipur Primary School Room No. - 2",
  "176 - Rambasan Primary School",
  "177 - Yogoda Satsangha Palpara High School Room No. - 1",
  "178 - Yogoda Satsangha Palpara High School Room No. - 2",
  "179 - Tota Falkara Primrary School",
  "180 - Yogoda Satsangha Palpara Primary School",
  "181 - Yogoda Satsangha Palpara Balika Vidyalaya (High)",
  "182 - Dhankar Primary School Room No. - 1",
  "183 - Dhankar Primary School Room No. - 2",
  "184 - Talchitkini Pirmary School Room - 1",
  "185 - Talchitkini Pirmary School Room - 2",
  "186 - Barmukhal Primary School",
  "187 - Sahapur Swapneswar Primary School Room No. - 1",
  "188 - Sahapur Swapneswar Primary School Room No. - 2",
  "189 - Golara Adarsha Primary School Room No. - 1",
  "190 - Golara Adarsha Primary School Room No. - 2",
  "191 - Rupadighi ICDS",
  "192 - Chistipur Primary School (West)",
  "193 - Chistipur Primary School (East)",
  "194 - Nankar Primary School",
  "195 - Baruibar Primary School",
  "196 - Barhat Jr. Basic High School",
  "197 - Maishali Primary School",
  "198 - Nakibasan Primary School",
  "199 - Ektarpur Primary School",
  "200 - Barhat Sambhunath Banipith (High)",
  "201 - Pratappur SSK",
  "202 - Payranagari Primary School",
  "203 - Kulrakhi Primary School",
  "204 - Katranka Primary School",
  "205 - Sadatpur Primary School",
  "206 - Dulalpur SSK",
  "207 - Barabhagia Jr.  Basic School",
  "208 - Saiyadpur Primary School",
  "209 - Sankargeria SSK",
  "210 - Ashariabandh Primary School",
  "211 - Kutubpur Primary School",
  "212 - Hirasagar Primary School Room No. - 1",
  "213 - Hirasagar Primary School Room No. - 2",
  "214 - Kantapukhuria SSK",
  "215 - Paharpur Primary School",
  "216 - Singda Primary School",
  "217 - Makrampur Nilkantha Sikshasadan Room No. - 1",
  "218 - Sahapur Primary School",
  "219 - Makrampur Nilkantha Sikshasadan Room No. - 2",
  "220 - Khakuriadanga Primary School",
  "221 - Goalda Primary School",
  "222 - Goalda SSK",
  "223 - Banamalichak Primary School",
  "224 - Tarat Primary School Room No. - 1",
  "225 - Tarat Primary School Room No. - 2",
  "226 - Irda Prathamik School",
  "227 - Ramchandra Primary School",
];

export const PATASHPUR_2_OPTIONS = [
  "56 - Kanpur Prathamik vidyalay ",
  "57 - Kanpur Shriguru Siksha Niketan ",
  "58 - Dainda Prathamik vidyalay ",
  "59 - Jhuria Jr. High School ",
  "60 - Kekai Prathamik vidyalay ",
  "61 - Bamunda Prathamik vidyalay (Dakshin)",
  "62 - Bamunda Junior High School ",
  "63 - Krishnapur Special Prathamik vidyalay ",
  "64 - Itachana Prathamik vidyalay ",
  "65 - Matirampur S.S.K. ",
  "66 - Haridangar High School ",
  "67 - Patashpur (Tupchibarh) Prathamik vidyalay (Purba)",
  "68 - Patashpur (Tupchibarh) Prathamik vidyalay (Paschim)",
  "69 - Chaksrikrishna Prathamik vidyalay ",
  "70 - Madhya Kashba S.S.K ",
  "71 - Selampur Prathamik vidyalay (Paschim)",
  "72 - Selampur Junior High School ",
  "73 - Patashpur Harocharan Vidyapith ",
  "74 - Kasba Patashpur Prathamik Vidyalay ",
  "75 - Satshanda Prathamik vidyalay ",
  "76 - Srikhoda Prathamik vidyalay ",
  "77 - Raghunathpur Muradpur Prathamik vidyalay ",
  "78 - Manpur Prathamik vidyalay ",
  "79 - Girisha Prathamik Vidyalay ",
  "80 - Gangasagar Primary School ",
  "81 - Mustafapur Yashoda Satsanga vidyapith (North)",
  "82 - Mustafapur Yashoda Satsanga vidyapith ",
  "83 - Barh Mustafapur Saifur S.S.K ",
  "84 - Nonakourda Prathamik vidyalay (Purba)",
  "85 - Nonakourda Sukanta S.S.K. ",
  "86 - Paschimsai Prathamik vidyalay ",
  "87 - Khar Paschimpara Prathamik vidyalay ",
  "88 - Baharda Prathamik vidyalay ",
  "89 - Khar Highschool (Uchchamadhyamik ) ",
  "90 - Ratanpur Primary School ",
  "91 - Dakshin khar S.S.K. ",
  "92 - Purba Khar S.S.K ",
  "93 - Barbatia Highschool ",
  "94 - Buran Prathamik vidyalay ",
  "95 - Kalyanpur Prathamik vidyalay (Dakshin)",
  "96 - Kalyanpur Prathamik vidyalay (Uttar)",
  "97 - Kainara Prathamik vidyalay ",
  "98 - Kainara Jr. High School ",
  "99 - Nimja Prathamik vidyalay ",
  "100 - Purushottampur Highschool ",
  "101 - Purusottompur Primary School ",
  "102 - Kashipur Prathamik vidyalay ",
  "103 - Pindarui Prathamik vidyalay ",
  "104 - Panchetgarh Prathamik vidyalay (Uttar)",
  "105 - Panchetgarh Prathamik vidyalay (Purba)",
  "106 - Panchetgarh Highschool (Paschim)",
  "107 - Panchetgarh Highschool (Dakshin)",
  "108 - Chandanpur Chaksuja Prathamik vidyalay (Uttar)",
  "109 - Chandanpur Chaksuja Prathamik vidyalay (Paschim)",
  "110 - Kharui Garh High School (Uttar)",
  "111 - Kharui Garh High School (Dakshin)",
  "112 - Lachhubarh Prathamik vidyalay ",
  "113 - Gobardhanpur S.S.K ",
  "114 - Khatuabarh Prathamik vidyalay ",
  "115 - Rautara Prathamik vidyalay ",
  "116 - Kharui Kailaschandra Uchcha Prathamik vidyalay ",
  "117 - Kharui M.I. Senior Madrasha ",
  "118 - Gobardhanpur Prathamik vidyalay ",
  "119 - Barakonyarda Board Prathamik vidyalay (Dakshin)",
  "120 - Barakonarda Junior High School ",
  "121 - Bagmari Highschool ",
  "122 - Bagmari Primary School ",
  "123 - Tikrapara Ambikamoyee Highschool ",
  "124 - Pariharpur Prathamik vidyalay ",
  "125 - Jagti Deulbarh Harijan Primary School ",
  "126 - Jagati Uchha Prathamik vidyalay ",
  "127 - Krishnanagar Prathamik vidyalay ",
  "128 - Mangalpur Prathamik vidyalay Room 1",
  "129 - Mangalpur Junior High School ",
  "130 - Majna Radhakrishna Prathamik vidyalay Room - 1",
  "131 - Majna Radhakrishna Prathamik vidyalay Room - 2",
  "132 - Srirampur Haraprasad Highschool ",
  "133 - Kishornagar Patna Prathamik vidyalay ",
  "134 - Dhusurda Board Prathamik vidyalay ",
  "135 - Dhusurda Board Prathamik vidyalay (South)",
  "228 - Bhairabdanri Junior High School ",
  "229 - Bhairabadanri Prathamik vidyalaya (Dakshin)",
  "230 - Southkhanda Prathamik vidyalay ",
  "231 - Southkhanda West Primary School ",
  "232 - Chakbhabani Harijan Prathamik Vidyalay ",
  "233 - Chakbhabani Madan Kishor Nirodamayee vidyayatan ",
  "234 - Bamanbarh Jr. High School ",
  "235 - Ghonga Sashanka S.S.K ",
  "236 - Uttar Choumukh Harijan Prathamik vidyalay ",
  "237 - Sukhakhola Prathamik vidyalay ",
  "238 - Gopalpur Primary school ",
  "239 - Mallikpur Harijan Prathamik vidyalay ",
  "240 - Mallikpur Bajanbarh S.S.K ",
  "241 - Bara Udaypur Anath Board Prathamik vidyalay ",
  "242 - Patna Prathamik Vidyalay ",
  "243 - Chhotoudaypur Gopinath Prathamik vidyalay (Uttar)",
  "244 - Chhotoudaypur Gopinath Prathamik vidyalay (Dakshin)",
  "245 - Brajakishorpur Deshapran Gangaram High School ",
  "246 - Brajakishorepur Primary School ",
  "247 - Agraniya Prathamik Vidyalay ",
  "248 - Batia Byomkeswar Prathamik vidyalay ",
  "249 - Bhattabarh Primary School ",
];
